### ISSUE TITLE
An I/O callback for "write" in stb_image.h

### ISSUE THREAD

**Issue by ryanjpearson** [nothings/stb#1059]
It's great that stb_image.h offers callbacks to stream in!  I would love to see a "write" callback that would allow me to stream out the output.  I'm trying to run this in a micro-controller and I don't have the memory required to hold a whole decoded image from a PNG.  Thanks!

**Comment by nothings** [comment]
use libpng for this, the intent of the design of stb_image is for devices that have plenty of memory explicitly so we don't have to worry about this kind of thing

**Comment by ryanjpearson** [comment]
Why is output callback not appropriate but input is?  Not to argue, I'm new
to png decompression and curious.  My guess is that the output gets decoded
non-contiguously?

**Comment by nothings** [comment]
there's two things.

one is that it's basically not possible for the reason you say: PNG and JPEG both have interlaced/interleaved formats that decode in extremely non-contiguous order, and even w/o that jpeg files can require partial decoding of multiple channels before decoding. TGA and BMP are normally coded from bottom-to-top.

two, it's because it's about keeping the library simple. adding an input callback was straightforward because we already read the input incrementally. but the library was not designed to do the same for output, and doing it the naive way wouldn't solve all problems. for example, PNG decompresses the entire file before converting it from raw data to PNG data. only changing it to an output callback wouldn't change the fact it would still allocate a full-sized image to store the decompressed data. doing the extrra work to avoid that is out of scope for the design.

libpng and libjpeg were explicitly designed to support this (when possible, given interleaving etc).
