### ISSUE TITLE
Shifting signed 32-bit value by 31 bits is implementation-defined behaviour

### ISSUE THREAD

**Issue by zchrissirhcz** [nothings/stb#1061]
Hi, stb Authors

I'm using stb_image.h and using strict checking tools (such as cppcheck) for code quality ensurement. 

I noticed in stb_image.h there is a cast, from unsigned int to signed int, then do shifting:

https://github.com/nothings/stb/blob/b42009b3b9d4ca35bc703f5310eedc74f584be58/stb_image.h#L2093

And my checking rule report complains that:

>Shifting signed 32-bit value by 31 bits is implementation-defined behaviour

Can we just remove the type cast? What is the purpose we do cast here?

**Comment by adamkewley** [comment]
It may not *seem* necessary, but the low-level behaviour--in terms of what the compiler emits--does actually differ. 

Shifting a signed value in x86 results in SAR (arithmetic right-shift), while shifting an unsigned value results in an SHR (logical right-shift). This is observable in (e.g.) godbolt:

https://godbolt.org/z/rf1Wve

Where the difference between the two is how the sign bit is extended:

https://c9x.me/x86/html/file_module_x86_id_285.html

As for how implementation-defined that is, :shrug:. Almost all real architectures are using 2's complement, which has the handy side-effect of negative numbers having the MSB set, but other architectures may handle sign-bit-extension differently. The rounding side-effect (rounding down vs. towards infinity) doesn't matter here.

What may matter, in that specific codeblock is how `sgn` is used later:

https://github.com/nothings/stb/blob/b42009b3b9d4ca35bc703f5310eedc74f584be58/stb_image.h#L2099

```
k + (stbi__jbias[n] & ~sgn);
```

Without casting, the compiler will perform a logical shift, yielding (e.g.): `0b0000000000000001`, whereas with the cast you get `0b1111111111111111`. That usage is as a multi-byte mask, so the difference is significant.

**Comment by adamkewley** [comment]
For completeness, a more-portable equivalent would be something like:

```c++
#include <stdint.h>
#include <limits.h>

int clever(uint32_t v) {
    return (int32_t)v < 0 ? ~0 : 0;
}
```

Which emits (post-optimization):

```asm
clever(unsigned int):
        mov     eax, edi
        sar     eax, 31
        ret
```

This assumes that the multi-byte unsigned number can be bitcasted to a signed equivalent, which is *generally* safe, but if the unsigned 32-bit words are actually (e.g.) raw bytes read from a file then it would also be advisable to have a decoding function (that, e.g. decodes the multi-byte word into a signed integer). In that ("clean") case, most compilers will notice that the decoding step ultimately does nothing (assuming the format matches the CPU arch) and will elilde the computation away entirely (e.g. this happens when writing little-endian & big-endian decoders)

**Comment by rygorous** [comment]
This is now fixed in the dev branch and will be in the next version.
