### ISSUE TITLE
stb_truetype.h can't read standard windows font wingding.ttf

### ISSUE THREAD

**Issue by rds1983** [nothings/stb#1086]
This code throws an assert:
```C
	stbtt_fontinfo font;
	unsigned char ttf_buffer[1000000L]; 
	FILE* fp = fopen("c:/windows/fonts/wingding.ttf", "rb");
	fread(ttf_buffer, 1, sizeof(ttf_buffer), fp);
	fclose(fp);

	int fontOffset = stbtt_GetFontOffsetForIndex(ttf_buffer, 0);
	int r = stbtt_InitFont(&font, ttf_buffer, fontOffset);

	assert(r);
```

If I change "wingding.ttf" to, say, "arial.ttf", then it works.

**Comment by nothings** [comment]
wingding.ttf does not have a table mapping from unicode codepoints to font indices,
so stb_truetype has no way for you access the characters in the font, since stb_truetype
only works with unicode.

you could try moving the assigment of indexToLocFormat in line 1487 up a couple lines
to immediately before the preceding if(). it will still return 0, but you can ignore that, and
you might at least be able to access the font using the functions that take a 'glyph index'
instead of a unicode codepoint.

**Comment by rds1983** [comment]
cool, thanks for the thorough answer!

**Comment by nothings** [comment]
Probably this issue is not the same issue as the one you reported on imgui-sfml. However, I don't know what "all *.ttf fonts" means, and I don't know anything about how IMGUI, imgui-sfml, or SF::Font work so it's impossible for me to comment in more detail on what's going wrong with those.

To address an issue here, I need a copy of a specific TrueType file that doesn't load.

Of course, if you give me a ttf file that doesn't work, I may just say "That's not a TrueType file, that's an OpenType file which uses the .ttf extension but uses features outside of TrueType, which stb_truetype doesn't support". So you may be better off posting more than one failing ttf file.

(If they are standard windows files from the Windows/Fonts directory, I probably have them already and you just need to name them, not post them.)

**Comment by Hoek67** [comment]
Hi... I found a solution. ImGUI expects there to be a index_map by the looks.

I added a bit of code before the load to look at the font info and skip loading if index_map was 0.

The fonts that made ImGui not make a bitmap were webdings.ttf symbols.ttf etc. They have glyphs that are not associated with unicode characters and would be rererenced by index.

[code]
	stbtt_fontinfo info;

					gobMemFile mf;

					Resources.LoadResource(full, mf);

					int valid = false;

					if (!stbtt_InitFont(&info, (const unsigned char *)mf.GetBuffer(), 0))
					{
						
					}
					else // valid file... but does it have an index map?
					{
						if (info.index_map)
						{
							valid = true;
						}
					}
					
					Resources.FreeResource(mf);

					if (valid)
					{
						ImFont* fnt = fa.AddFontFromFileTTF(full, 20.0f, &config, ranges.Data);
						cnt++;
					}				
[/code]

After adding a bit of validation code before the load into ImGui I suddenly get all the fonts enumerated.

![image](https://user-images.githubusercontent.com/18671600/173669522-1e2bbccd-a21f-4189-9535-a8d4c240d347.png)
