### ISSUE TITLE
Little problem loading PSD files.

### ISSUE THREAD

**Issue by SpartanJ** [nothings/stb#109]
Hi Sean!
This is something that i reported some time ago in the MollyRocket forums but it never got fixed.

There's a little problem with the channels count returned in the PSD loading.
The PSD files are always loaded as 4 channels images, but the `comp` parameter returns the REAL number of channels of the image. So if i load a 3 channels PSD image, i don't know the final number of channels to use to load the image for example in OpenGL. I don't know if i'm being clear. But the problem is: i load a 3 channels PSD image, the image is returned correctly ALWAYS as a 4 channels image, but `comp` returns 3, and it should return 4, since the final image is 4 channels.
( `if (comp) *comp = channelCount;` should be `if (comp) *comp = 4;` )

In the forum i proposed to use the real channel count ( instead of using 4 channels, read the number of channels and create a the image with the channels count ). But i can't remember why you didn't want that solution.

Every time that i update stb_image in SOIL2 i've to patch this. It would be awesome to have this fixed, in any of the two ways mentioned.

Regards

**Comment by nothings** [comment]
Looking at the code, I think the reason I don't want to use the real channel count is because the meaning would be different from stb_image's channel count.

At least as the code is written (it's not my code), it assumes that a PSD file with two channels contains R & G (and expands that out to RGBA). But in stb_image, and image with two channels MUST be Y (luminance, aka grey value) & A.

For channelCount = 3 & 4, it would match, so if photoshop can only output 3 or 4, then it would be fine, but I haven't checked the specification.

I have fixed it to the other thing locally, it'll be fixed in the next version.

**Comment by SpartanJ** [comment]
Thanks Sean! ( the mingw patch for 32 bits builds it's fine now, thanks for that too! )
