### ISSUE TITLE
Plug-able external image formats support for stb_image.

### ISSUE THREAD

**Issue by SpartanJ** [nothings/stb#110]
This is a proposal for an enhancement that I've been thinking about for my use case in particular.

I've added some new image formats support in stb_image ( DDS, ETC1 and PVR ) for SOIL2, that i can't just propose to add to stb_image for various reasons ( licensing and because it doesn't make sense to add them in stb_image ). Every time that a new stb_image version rolls out I've to add this formats manually, and it's a little tiresome. But this could be easily solved if we add some function to plug-in the new format into stb_image, something like `stbi_add_new_format( struct with_required_function_pointers )`.

I know that this is a very specific use case, but i think that it wouldn't harm anyone, and you would be doing me a big favor to keep SOIL2 up to date against stb_image.

Thanks in advance,
Regards!

**Comment by nothings** [comment]
There used to be support for installable file formats, and I removed them in version 1.30, 2011-06-11.

Can you just wrap the stbi stuff?

```
unsigned char *my_load(unsigned char *data, size_t len, int *w, int *h, int *comp, int req_comp)
{
    if (test_my_file_format_1(data,len))
       return load_my_file_format_1(data,len,w,h,comp,req_comp);
    if (test_my_file_format_2(data,len))
       return load_my_file_format_2(data,len,w,h,comp,req_comp);
    return stbi_load(data, len, w, h, comp, req_comp);
}
```

**Comment by SpartanJ** [comment]
Yes! I can do that too, the reason i don't like that solution is that I've to test against the least used formats first ( or let stbi_load to fail ) and that i tend to use stbi_load also in other parts of my programs. But i'm OK if you don't wan't to add this again.
Thanks anyways!

**Comment by r-lyeh** [comment]
I'd like this feature to be re-added if possible too :)

**Comment by nothings** [comment]
Nah, I'm not going to do it. It's just too much of a mess for too little benefit since you can wrap it.

For example, many things are pluggable--the allocator, the IO, etc. An installable format would also have to access those things, but they're mostly defined internal to stb_image, and so they'd have to be exposed explicitly, etc. Whereas if you're wrapping it explicitly, you know almost always know whether you're plugging those things and can access them directly (or not) as needed.

So it doesn't feel like the right choice to me.
