### ISSUE TITLE
stb_image.h won't compile with warnings as errors.

### ISSUE THREAD

**Issue by chriscamacho** [nothings/stb#1128]
yes my setting are "strict" (ish) but in the long run it saves a lot of time...

```
include/stb_image.h:4123:10: error: comparison of integer expressions of different signedness: 'int' and 'long unsigned int' [-Werror=sign-compare]
 4123 |    if (b >= sizeof (z->size)) return -1; // some data was corrupt somewhere!
```

**Comment by chriscamacho** [comment]
```
include/stb_image.h: In function 'stbi__load_gif_main':
include/stb_image.h:6779:11: error: variable 'delays_size' set but not used [-Werror=unused-but-set-variable]
 6779 |       int delays_size = 0;
      |           ^~~~~~~~~~~
```

**Comment by bhshp** [comment]
@chriscamacho  I ran across this issue as well. For the first one, simply add a `static_cast` like `if (b >= static_cast<int>(sizeof (z->size))) return -1;` is ok. For the other one, just remove relevant set-value operation from file. I'd like to make a pull request to this repo.

**Comment by bhshp** [comment]
#1098 Actually there's a pr already,

**Comment by rygorous** [comment]
We will fix specific warnings if they cause trouble for enough people but building without warnings on all supported targets is an explicit non-goal, simply because there have been several instances in the past where a fix introduced to compile without warnings on compiler A then caused a warning on compiler B. This gets substantially worse when higher warning levels are involved.

The specific warnings in question seem to already have their own issues so I'm closing this one.
