### ISSUE TITLE
Hard limit too small on stbi__gif_lzw array when decoding GIF

### ISSUE THREAD

**Issue by erwanmaigret** [nothings/stb#1140]
I'm hitting cases of GIF where the number of LZW codes goes beyond 8192. I needed to bump it up on my end to allow loading of such GIF.

I was wondering if I was the only person to hit this issue and what is the math behind this hardcoded limit of 8192

**Comment by nothings** [comment]
The original GIF specification from 1987 limits it to 4095 codes. I don't know the details beyond that, but I suppose there was some expanded version that allowed 8192 codes when the code was written. Maybe there is some even newer expanded version that supports more codes. Can you open the GIF in photoshop or other commonly-used tools?

**Comment by erwanmaigret** [comment]
Yes the GIF is fine in photoshop and preview on Mac.

**Comment by nothings** [comment]
the spec calls for a limit of max code of 4095. i don't know why the limit in that code is 8192, because images generated assuming a limit of 4095 would break once you went higher. i also don't know why it throws an error if the code table fills up; it should just keep running without generating new codes.

you could try changing line ~6566 from 'if (oldcode >= 0)' to 'if (oldcode >= 0 && avail < 4096)' and see if that fixes it. (or maybe 4095)

**Comment by rygorous** [comment]
The GIF89a spec (newer than the GIF87 version) also explicitly limits the maximum code length to 12 bits and the maximum legal code to 4095. It does not surprise me that there are malformed files in the wild (there always are) but this is explicitly disallowed.

There are known issues with the GIF decoder, but sticking to normative limits in the spec sounds fine with me; we need to fix bugs that cause bad/undefined/exploitable behavior on malformed files, but rejecting files that are explicitly outside the GIF spec is definitely fine for what stb_image's scope is.
