### ISSUE TITLE
stb_image.h: invalid YCbCr to RGB calculations

### ISSUE THREAD

**Issue by 89z** [nothings/stb#1164]
Based on ITU-T T.871 [1], the proper equation for YCbCr to RGB looks like this for the red channel:

~~~
R = Y + 1.402 * (Cr - 128)
~~~

or this with rounding:

~~~
R = Min(Max(0, Round(Y + 1.402 * (Cr - 128) )), 255)
~~~

Using this image [2], I wrote a program in Go using the exact formula, taking pixel `X:15,Y:0` just as a test:

~~~go
package main

import (
   "fmt"
   "image"
   "image/jpeg"
   "math"
   "os"
)

func main() {
   f, err := os.Open("Lenna50.jpg")
   if err != nil {
      panic(err)
   }
   defer f.Close()
   picture, err := jpeg.Decode(f)
   if err != nil {
      panic(err)
   }
   pic := picture.(*image.YCbCr).YCbCrAt(15, 0)
   r1 := float64(pic.Y) + 1.402 * float64(pic.Cr - 128)
   r := math.Min(math.Max(0, math.Round(r1)), 255)
   fmt.Println(r1, r) // 220.492 220
}
~~~

Now if I write a similar C program, I get a different result:

~~~c
#include <stdio.h>

#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"

int main() {
   int x, y, n;
   unsigned char *data = stbi_load("Lenna50.jpg", &x, &y, &n, 0);
   printf("%d %d %d\n", x, y, n); // 512 512 3
   printf("%d\n", data[15*3]); // 222
   return 0;
}
~~~

It seems the STB example is wrong. Even if STB rounded up, it would be 221, not 222.

1. <https://itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-T.871-201105-I!!PDF-E>
2. https://rosettacode.org/mw/images/3/3c/Lenna50.jpg

**Comment by 89z** [comment]
https://github.com/treeform/pixie/issues/241

**Comment by nothings** [comment]
The STB implementation is not wrong. JPEG images do not guarantee exactly identical RGB values on decode. (Another example is that no specification was given for how decimated CrCb are reconstructed to full resolution.)

To quote a footnote on YCbCr to RGB conversion from ITU-T T.871:

"As  this  Recommendation  |  International  Standard  is  based  on  the  prior  informally-circulated  JFIF  version  1.02  specification  that  was  produced  in  1992,  which  referenced  Rec.  ITU-R  BT.601  (formerly  CCIR  601),  it  references  that  specification  for  definition  of  the  E'Y, E'CB,  and  E'CR  signals  that  correspond  to  the  YCBCR  values  specified  herein.  However,  since the development of the prior JFIF version 1.02 specification, additional industry specifications have been developed, Rec. ITU-R BT.601 has been updated, and common industry practice has emerged which often follows the sYCC specification in IEC 61966-2-1/Amd.1.  **The  difference  between  the  use  of  the  colour  interpretation  specification  in  this  Recommendation  |  International  Standard  and  that  of  the  sYCC  specification  may  be  considered  negligible  in  practice.  Moreover,  as  previously  noted, the colour space specification herein can provide only a basic level of colour fidelity.**"

In your example, you used 64-bit float precision. Another implementation might use 32-bit float precision and compute a different result. Another implementation might use fixed-point arithmetic and compute a different result. Arguably, since the specification doesn't indicate precision, it should be computed with decimal arithmetic so the result can be computed precisely.

In practice, stb_image is designed to use the formulas from JFIF 1.02 but with reduced-precision integer math to be able to leverage SIMD operations, and the YCbCr computation on non-SIMD platforms uses the same reduced math for consistency. It doesn't make sense for us to try to match the results of a 64-bit floating point computation.

**Comment by 89z** [comment]
@nothings thanks for the fast and detailed reply. However I still have a few concerns.

1. Regardless whether I used `float64` or `float32`, I also included a rounded result, by which the STB implementation is off by a value of `2` as shown in the comments on the original post

2. The STB source in question is pretty large, can you point to the functions or lines of STB code that handle the calculations, so I can review them?

3. Do you have any link to the specification that you based the STB image code on?

**Comment by nothings** [comment]
1. as noted, the specification does not indicate how the values Cr/Cb are reconstructed. If your example has downsampled Cr/Cb channels, there may be an arbitrarily-large difference in those values if the reconstructions are different. So it's not just a question of rounding.
2. https://github.com/nothings/stb/blob/master/stb_image.h#L3567
3. https://web.archive.org/web/20120301195630/http:/www.jpeg.org/public/jfif.pdf

**Comment by 89z** [comment]
> 2. https://github.com/nothings/stb/blob/master/stb_image.h#L3567

Looks like for my system at least, the code in question is here:

https://github.com/nothings/stb/blob/8e51be04dc7dcee462e1f09e410faceab52cc6d2/stb_image.h#L3697-L3706

I did some more checking, it seems the problem is even before RGB is calculated. For example using the same image and pixel, with the Go code is get:

~~~
Cr - 128 = 46
~~~

while with STB code, I get:

~~~
Cr - 128 = 47
~~~

Do you know where or how the `pcr` array is populated?

https://github.com/nothings/stb/blob/8e51be04dc7dcee462e1f09e410faceab52cc6d2/stb_image.h#L3585

**Comment by nothings** [comment]
So, I mentioned from the very first that the issue was more likely to be Cr/Cb being different due to reconstruction. If you care about this stuff and don't know what that means, you're going to have to read the jpeg specification.

Since you haven't actually mentioned any bug here that you're trying to fix (stb_image producing results that differ from other implementations by +-2 is perfectly within reason), it's not a good use of my time to keep answering your questions.

**Comment by 89z** [comment]
@nothings thanks again for the information.

> Don't use a lossy-compression format if you want exactly identical results.

The results are different enough for me to notice, it starts with the YCBCr values, then propagates to the RGB value, to the point where if you run images comparisons like detailed on this page [1], it results in a `0.1%` difference between implementations. Thats significant to me.

So if the Go implementation is "wrong" I want to correct it to whatever STB is using. However that difficult, as you have said a couple of times that the CrCb reconstruction is unspecified, but you also havent pointed to where reconstruction actually happens. I apologize if I overlooked it.

1. <https://rosettacode.org/wiki/Percentage_difference_between_images>

**Comment by rygorous** [comment]
There are numerous parts about JPEG that are under-specified:
- The exact color space is not actually fully specified (stb_image tries to agree with what the IJG JPEG library does to within a reasonable approximation, since it's the de-facto standard for 30 years).
- When Cr/Cb are subsampled (stored at lower resolution; this is usually on except at very high quality settings), the position of the chroma sample grid relative to the luma samples is not specified by JPEG. JFIF picks one convention, Adobe JPEG uses another, digital video descended from the MPEG standards uses another one. (I don't remember offhand whether the Adobe and the MPEG conventions agree) The filters used for downsampling and reconstruction are also completely unspecified.
- The primary transform applied by JPEG decoders, the IDCT, is again not specified in the JPEG standard. The normative reference here is IEEE 1180 which also does not specify the transform, instead specifying bounds on the expected error in a certain number of random trials.

Some of these are oversights (e.g. I don't think the confusion regarding pixel sample locations was intentional), some of it was because the relevant algorithms were still an active research subject at the time of JPEG's publication (applies to the IDCT), and some (such as the fuzziness of the color space definition) was because all of this was really expensive at the time it was standardized and there was a desire to not constrain implementations too much.

The end result, however, is that there is a wide range of possible legal results that almost any given JPEG image can legally decode to, and +-2 errors on individual 8-bit pixels are well within what is allowed by the spec. You can have +-2 differences post-IDCT on each color channel for at least some pixels as per IEEE 1180 and still be compliant.

The particular choices made in stb_image mostly try to match the defaults of the IJG JPEG library, which as said is the de facto standard used by most programs. That means our IDCT tries to agree with their "slow integer" IDCT (the default), and furthermore unlike the IJG JPEG library (which also provides 2 other selectable IDCTs that give different results), we have only the one version. Our sampling locations and choice of reconstruction filters also match IJG, as do our color spaces, although the coefficients might be rounded slightly differently, I don't remember offhand. (IJG also uses a fixed-point approximation of coefficients, but don't remember which internal precision it uses). The final constraint we have that IJG doesn't is that we also have SIMD IDCT implementations for SSE2 (x86) and NEON (ARM) targets, and we want the decoder results to be the same with or without SIMD, so our choices of internal fixed-point precisions etc. were chosen to lead to efficient implementations for all three paths (SSE2, NEON, scalar fallback), which placed some additional restrictions due to limited value ranges and available operand precisions.

The actual YCbCr->RGB conversions in stb_image are in `stbi__YCbCr_to_RGB_row` (scalar) with the SIMD version right below it.

**Comment by 89z** [comment]
@rygorous thanks as well for the great background and information.

Essentially this is what I am trying to answer. On this page [1], you have many implementations across many different languages. But I noticed, that pretty much every single implementation results in either `1.626%` or `1.775%` difference in the two images.

My Go program results in the larger percentage difference, and STB results in the smaller difference. So I was hoping someone would say, "oh thats because Go is using an ABC algorithm, and STB is using an XYZ algorithm". I am still doing my own testing, but I havent found that answer that I am looking for yet.

1. <https://rosettacode.org/wiki/Percentage_difference_between_images>

**Comment by rygorous** [comment]
"Percentage difference between images" is not a conventional image difference metric.

As for Go's implementation, looking up the code, they use this https://github.com/golang/go/blob/master/src/image/jpeg/idct.go which as is noted in the file is a translation of the MPEG-2 reference decoder. It uses an IDCT algorithm descended from Wang's factorization (from 1984) in fixed point with 11 bits fractional precision and a final scaling of some of the results by 1/sqrt(2) with 8 bits fractional precision.

As mentioned before, stb_image uses an IDCT descended from IJG's "slow" algorithm, which is not actually slow; it is based on a 1989 algorithm by Loeffler, Ligtenberg and Moschytz that avoids having two successive rounding multiplies on any signal path (the Wang factorization used by the Go code does, it has the multiply by 1/sqrt(2) with low precision in the x2/x4 outputs; the decreased precision is to avoid overflow). The stb_image code uses 12 bits fractional precision for its coefficients.

So stb_image uses both higher internal working precision than the Go standard library code and an algorithm that avoids two reduced-precision, double-rounding steps present in the Go code. I haven't tried to validate either against a high-precision reference implementation but I would expect the stb_image code to have lower error.

**Comment by 89z** [comment]
@rygorous thanks for the great reply. I think I found the Go function that populates the YCbCr values, so I will look at that some more. Thanks again.

https://github.com/golang/go/blob/go1.16.5/src/image/jpeg/scan.go#L50-L51

**Comment by ValZapod** [comment]
> * the position of the chroma sample grid relative to the luma samples is not specified by JPEG

It is center. That is not the same as in AVC or HEVC for HDR.

**Comment by rygorous** [comment]
I already specified the details in the part you cut off, namely that JFIF (the most common format for JPEG files) specifies center sample locations, but the actual JPEG spec is silent on the matter, and there have been other (non-JFIF) variants that use different conventions. It's a mess all the way through.
