### ISSUE TITLE
Break out the regex/wildcard matching from stb.h

### ISSUE THREAD

**Issue by nothings** [nothings/stb#119]
Rewrite the old Boyer-Moore-esque regexp scanner into an stb header-file library, with an accompanying straight-ahead DFA scanner, and invite people to do performance comparisons with them.

**Comment by ocornut** [comment]
I briefly looked into extracting stb_wild\*, stb_regex_\*, stb_matcher_\* to a separate file for my own use.
However for the sake of making a proper transition (rather than just copy & pasting them), stb.h has a few dependencies on them,
- readdir_raw uses stb_wildmatchi()
- stua uses stb_lex_\* which is based on stb_matcher_\*

Do you know how you would you approach handling those dependencies? Would it acceptable that stb.h optionally depended on say, stb_match.h, to provide access to stua?

**Comment by nothings** [comment]
I think would just keep them in both places. Wrap them both in an

```#ifndef STB_REGEX
#define STB_REGEX
...
#endif
```

so they don't conflict if both are included (or rename everything in the new fork).

Note that stb regex stuff only does pure regex, it doesn't do grouping, back-references, or a lot of other stuff in e.g. PCRE.

**Comment by nothings** [comment]
I've moved the original "stb_sgrep" idea into https://github.com/nothings/stb/issues/203, so now this issue is just for the idea of splitting out existing regex/wildmatch.

**Comment by rygorous** [comment]
Ok this is just not going to happen in this form, closing.
