### ISSUE TITLE
half width voxels and vertically continous effect

### ISSUE THREAD

**Issue by kariem2k** [nothings/stb#124]
Most of my game objects are mostly vertical. So I want the half-height cubes and shared vheight to be applied for the width of the cube not the height of it. Can that be achieved by rotation or any work around?

Thanks

**Comment by nothings** [comment]
No, because you want them along two axes instead of just one. I.e. you could rotate the mesh to have half-height or vheight oriented north-south, but then you don't get east-west.

You could switch to blocks which are always twice as tall as they are wide, though. Then a half-height block would be a cube. Totally different effect, but potentially interesting. No solution for vheight, though. (I decided against putting in "horizontal slopes" because they would have used up to many of the geometry ids, and would be a lot more PITA to generate the meshes.)

**Comment by kariem2k** [comment]
Thanks. I will try the VH = 3 then VH = 1 idea and see the effect.
Also I was thinking to have 2 interleaving meshes, one will have blocks when the vertical effect needed most & built using VHeight smoothing normally but then rotate it like you said. the other one will use VHeight without rotation for other areas. But I think it will not very well for edges that need both directions smoothing.
