### ISSUE TITLE
stb_image fails to compile with SIMD on linux

### ISSUE THREAD

**Issue by avpdiver** [nothings/stb#1258]
**Describe the bug**
OS: Ubuntu 20.04
GCC: 11.1.0

> In file included from deps/stb/stb_image.h:723,
/usr/lib/gcc/x86_64-linux-gnu/11/include/emmintrin.h: In function ‘stbi_uc* stbi__resample_row_hv_2_simd(stbi_uc*, stbi_uc*, stbi_uc*, int, int)’:
/usr/lib/gcc/x86_64-linux-gnu/11/include/emmintrin.h:1230:10: error: the last argument must be an 8-bit immediate
 1230 |   return (__m128i)__builtin_ia32_pslldqi128 (__A, __N * 8);
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/11/include/emmintrin.h:1224:10: error: the last argument must be an 8-bit immediate
 1224 |   return (__m128i)__builtin_ia32_psrldqi128 (__A, __N * 8);

**Comment by rygorous** [comment]
PSLLDQ / PSRLDQ are _mm_slli_si128 / _mm_srli_si128, of which there are
exactly one use in stb_image each (in `stbi__resample_row_hv_2_simd`),
namely these two lines:

```
__m128i prv0 = _mm_slli_si128(curr, 2);
__m128i nxt0 = _mm_srli_si128(curr, 2);
```

Those are integer constants. Whatever is going wrong is not on our side.

-Fabian

**Comment by nothings** [comment]
Note the "_N * 8" in the quoted source code line, which makes it sound like those instructions are being used to emulate some other instruction.

**Comment by rygorous** [comment]
No, that's the official definition of those intrinsics for GCC/Clang, and has been for over 11 years: https://cfe-commits.cs.uiuc.narkive.com/oT2kv86T/r115374-in-cfe-trunk-lib-sema-semachecking-cpp-test-sema-x86-builtin-palignr-c

It's trying to match some historical artifact in the way GCC exposed these builtins (which took a shift amount in bits but required it to be a multiple of 8).

Around 2018, Clang renamed their internal built-in to __builtin_ia32_pslldqi128_byteshift which takes a byte amount, and then removed the now unnecessary *8 from their emmintrin headers: https://lists.llvm.org/pipermail/cfe-commits/Week-of-Mon-20180611/231938.html

Sounds like for whatever reason the bug reporter ends up with a GCC emmintrin.h for a LLVM-based compiler, which won't work since it tries to use the wrong built-in.

**Comment by rygorous** [comment]
For context, GCCs emmintrin.h defines the intrinsics as functions, which doesn't work on Clang, because the shift amount argument isn't technically a compile-time constant if it's just the N argument in a regular function:

https://github.com/gcc-mirror/gcc/blob/master/gcc/config/i386/emmintrin.h#L1228

that looks like the exact version that compile-time error came from (at time of writing, I didn't bother baking the current commit ID into the URL)

For Clang/LLVM compiles, it should be using the Clang/LLVM version of that header, which has to use a #define to obey with Clang's semantics rules:

**Comment by nothings** [comment]
Note that the reporter CLAIMED it was a gcc build, so I'm not 100% sure what's going on, but clearly it's an issue with the build and not with stb_image. Closing.

**Comment by gilmar-sales** [comment]
The last parameter must be a compile-time value for optimization purposes in  newer versions of the `emmintrin.h`, maybe the stb code doesn't provide some inline variable in **Debug** but the compiler force it in the **Release** build, if you just need to build in **Debug**, there's a workaround by turning off the `emmintrin.h` optimization too (**Be careful to not use this(shit) into header files that uses __OPTIMIZE__**):

```
#ifndef NDEBUG
    #undef __OPTIMIZE__
#endif
#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"

#ifndef NDEBUG
    #define __OPTIMIZE__ 1
#endif
```
