### ISSUE TITLE
stb_sprintf: callback takes const char *?

### ISSUE THREAD

**Issue by scurest** [nothings/stb#1262]
Hi, I'm wondering why the callback for stbsp_vsprintfcb takes a `char const * buf` instead of a `char * buf`.

I'm using the callback to copy out the data and then `return buf` to reuse the same buffer, but this requires casting away const.

Is this safe? Is `buf` always the same pointer the user provided (cast to const)? Is there a reason the callback isn't passed a non-const `buf`?

Thanks.

**Comment by nothings** [comment]
It's passed as const because you're not expected to write into it.

The intent is that you use the void* user pointer to keep track of any additional information you need. For example, this could be a context structure containing the buffer you're building. So the expected use if you wanted to repeatedly copy to the same intermediate buffer is that you would store that intermediate buffer in the context as well and return it, so no cast would be necessary.

I believe that the same buffer is always returned to you, but I don't think this is actually intended to be guaranteed by the API, though it's hard to imagine a scenario where it wouldn't be true. So it's probably ok to return the passed-in pointer, but it's definitely not the intended use, so requiring a cast seems perfectly reasonable to me.
