### ISSUE TITLE
[stb_truetype, Ubuntu] Can't 'find_table' for Ubuntu .ttf font

### ISSUE THREAD

**Issue by Jony01** [nothings/stb#1304]
**Describe the bug**
I found on Ubuntu font _"/usr/share/fonts/truetype/noto/NotoColorEmoji.ttf"_ when I try to initialize the font by function `stbtt_InitFont`. InitFunction ends inside `stbtt__find_table`, which return 0 and disallow initialization of the font.

**To Reproduce**
Run test and see it is uninitializabled font.
```
TEST_CASE("Initialize NotoColorEmoji") {
    std::string font_path = "NotoColorEmoji.ttf";
    FILE *file = fopen(font_path.c_str(), "rb");
    REQUIRE(file != nullptr);
    // find size of file
    REQUIRE(fseek(file, 0L, SEEK_END) == 0);
    size_t size = ftell(file);
    REQUIRE(size != 0);
    rewind(file);
    std::vector<unsigned char> buffer(size);
    size_t count_loaded_bytes = fread((void *) &buffer.front(), 1, size, file);
    REQUIRE(count_loaded_bytes == size);
    int font_offset = stbtt_GetFontOffsetForIndex(buffer.data(), 0);
    REQUIRE(font_offset >= 0);
    stbtt_fontinfo font_info;
    CHECK(stbtt_InitFont(&font_info, buffer.data(), font_offset) != 0); 
}
```

**Expected behavior**
All *.ttf files are able to initialize.

**At begin**
Could you please confirm that attached TrueType font is valid?
[NotoColorEmoji.zip](https://github.com/nothings/stb/files/8187033/NotoColorEmoji.zip)

**Comment by Jony01** [comment]
Sorry, it is my mistake because I need to use version from [imgui](https://github.com/ocornut/imgui). [[link](https://github.com/ocornut/imgui/blob/master/imstb_truetype.h)]


This is fixed in an actual version.

**Comment by Jony01** [comment]
Call of `stbtt__find_table(data, fontstart, "CFF ");` is on line 1714 and return zero.

**Comment by nothings** [comment]
It's pretty clear from the name, since TrueType has no support for multi-colored characters; it's not actually a TrueType font, it's some extended OpenType font (which also use ".ttf" most of the time), but not one that we support. (We only support classic TrueType and also Type 1 CFF fonts.)

Windows 7 built-in font viewer also does not recognize it.

See the documentation [Using NotoColorEmoji](https://github.com/googlefonts/noto-emoji#using-notocoloremoji):
>NotoColorEmoji uses the CBDT/CBLC color font format, which is supported by Android and Chrome/Chromium OS. Windows supports it starting with Windows 10 Anniversary Update in Chrome and Edge. On macOS, only Chrome supports it, while on Linux it will support it with some fontconfig tweaking

stb_truetype has no way to handle colored characters anyway, and we do not intend to add one, so this font will never be supported by stb_truetype
