### ISSUE TITLE
Please add support for XYZE Radiance .hdr files

### ISSUE THREAD

**Issue by TomArrow** [nothings/stb#1323]
**Is your feature request related to a problem? Please describe.**
Radiance .hdr does not support negative values. Thus, any out-of-gamut colors get clipped in the normal RGBE format. Meaning, the range of colors that can be displayed with normal .hdr files is limited to the sRGB gamut (in a typical context like reading .hdr files as textures in a non-color-managed context). There's also the XYZE variation of .hdr. XYZE saves values in the XYZ color space instead which encompasses all visible colors. 

**Describe the solution you'd like**
Support reading/writing of XYZE files. Treat them like normal linear sRGB images. When writing, convert from the input values from linear sRGB to XYZ. When reading, convert from XYZ to linear sRGB. It is a simple matrix transform. Thus, effectively, negative values are allowed to the degree necessary to cover the colors perceivable by humans.

**Describe alternatives you've considered**
Alternative solutions: Treat the XYZE values as raw without any conversion, but let the calling application know/set that the .hdr file is a XYZE file so the application can do its own conversion. Yet another solution if the assumption of the data being linear sRGB is not desired: Provide a reading/writing function for .hdr files that allows to specify the chromacity and white coordinates, which then can be used to generate the correct conversion matrix. This way any arbitrary RGB color space could be assumed.

**Additional context**
That's about it I think.

**Comment by rygorous** [comment]
This is asking for an incredibly niche feature in an already incredibly niche image format for `stb_image`, and it would complicate the API because we'd now need to add a way to pass color space information. Everything else in the library works with RGB data and wherever possible just passes the raw values from the file through, leaving interpretation to the app.

I consider this out of scope for stb_image. Feel free to add this in a private fork but we're not going to make it an official feature.
