### ISSUE TITLE
stb_truetype: Size-dependant and font-dependant sharpness and baking artifacts

### ISSUE THREAD

**Issue by FrostKiwi** [nothings/stb#1335]
Different fonts have a different "sharp font-size". A font-size, that properly produces well formed and sharp glyphs. Stepping outside of those sizes results in weird appearances, like cut-off letter sides and un-sharp letters. This behavior is dependent on the font. When baked by stb_truetype, each font presents a range of sharp font sizes and stepping outside of them results in un-sharp drawing.

Here is a size comparison. [Click ](https://raw.githubusercontent.com/FrostKiwi/Nuklear-wiki/main/Bad-size-good-size.gif)to see the gif 1:1 unscaled in the browser, so image scaling does not affect the appearance.
[![](https://raw.githubusercontent.com/FrostKiwi/Nuklear-wiki/main/Bad-size-good-size.gif)](https://raw.githubusercontent.com/FrostKiwi/Nuklear-wiki/main/Bad-size-good-size.gif)
Note the unsharp appearance going from a good size to an unsharp size and note the letter B in "Bad", which has it's bottom side cut off by a pixel.

Various workarounds are presented in Nuklear's complete font guide in the ["font sharpness"](https://github.com/Immediate-Mode-UI/Nuklear/wiki/Complete-font-guide#font-sharpness) chapter.

This has been reported multiple times from multiple angles, I just want to open up this issue to introduce the connection, that it's font-dependent and size-dependent. One interesting tid-bit is that a set of sharp sizes also comes in discrete integer steps. For instance, 27.25, 32.25, 37.25 etc. for a font may all appear sharp, all integer step 5 apart. (An integer step, that also depends on the font) However, there are also other sharp font sizes outside these integer steps.

**Comment by nothings** [comment]
Some blurring is absolutely fundamental to how non-hinted fonts work. Sharpness can be improved to a limited extent by snapping to pixel coordinates or by using the oversmaple facility, but there are limits since a single-pixel-wide stroke in a font can always fall on two source pixels. Maximum sharpness on RGB LCD/LED displays is achieved using subpixel rendering, which is outside of the scope of stb_truetype.

Shapes being cut-off is likely to be an error in the user rendering/compositing, not in stb_truetype. Without a specific repro showing the problem directly in the bitmap output by stb_truetype, I'm not going to act on it. Reopen if you want to provide such a reproducible case.

**Comment by FrostKiwi** [comment]
Thank you for providing some insight.
