### ISSUE TITLE
stb_voxel_render color precedence

### ISSUE THREAD

**Issue by friesencr** [nothings/stb#137]
https://github.com/nothings/stb/blob/master/stb_voxel_render.h#L1998

The blocktype.color has precedence over the input.color.  I think it should be the other way around.

**Comment by nothings** [comment]
The design is that if the block color is defined and non-0, the block color wins, otherwise the input color wins. So you can just set the block color to be always 0 so the input color will always be used (well, you just don't define the blocktype color).

The main advantage I can think of for either approach is that IF you have a scenario where the block type usually implies the color, but for some blocktypes you need to specify the color separately, then with the current approach you never need to touch input.color; you can leave it with uninitialized garbage. (To fully gain the benefit of this I need to reorder the logic so that input.color is only loaded if blocktype color was non-0.) There's no corresponding advantage for the other direction, because using blocktype is "free" cachewise (it only requires touching a 256-entry palette), whereas input.color is alawys a full extra memory reference.

Can you think of a scenario where having input.color take precedence would actually provide more functionality or have better performance?

**Comment by nothings** [comment]
Also, I think the original motivation was because input.block_color_face is actually more expressive -- it lets you specify independent colors for each face which you can't do with input.color. So it made sense for that to take precedence. So I made input.block_color have the same precedence as input.block_color_face for consistency/simplicity because it mostly doesn't matter.

It is true that this stuff should be documented more clearly.

**Comment by friesencr** [comment]
I feel like the 3d indexed fields should generally override the blocktype fields.  But in the case of the faces where the faces are clearly more expressive, the faces should definitely win.   

stbvox can easily take a performance first stance too.   

Yes I was spot changing a color to override the blocktype.  I turned off textures to test some things.  Most people should be using textures over colors though. 

I am probably a month or so out from starting on the tooling.  From a tooling standpoint I see having an interface for blocktypes and an interface for each block.  I haven't tried nearly all the permutations yet but as an end user I would expect individual changes to work over the blocktype because of specificity.

I am sure there will be wierdnesses with precedence.  I don't know if it can be solved in a consistent manner.  

Since there isn't anything wrong with your code do you want the issue closed?

**Comment by nothings** [comment]
No, it's worth considering.

**Comment by nothings** [comment]
Anyway, the thing does have an explicit separate set of parameters (ecolor) for overlaying colors on particular faces, but only according to certain limitations. (The idea there is to e.g. allow recoloring decals where you're limited in how frequently you can apply the decals.) One of the core constraints of stb_voxel_render is that you are limited in what you can express to the mesher, even though the vertex format + shader could potentially express more.

Certainly one intention though is to revise what you can express with the mesher as we explore the current setup and discover its limitations.

**Comment by nothings** [comment]
I'm thinking now the best approach is to make it configurable; default to performance-optimal, and let you #define it to get a different trade-off.

**Comment by nothings** [comment]
I'm closing this as the library simply doesn't have enough uptake to worry about it. Users can always change the library if they don't like the default behavior.
