### ISSUE TITLE
Consider using CC0 LICENSE instead of dual MIT/Unlicense

### ISSUE THREAD

**Issue by aviallon** [nothings/stb#1405]
The **CC0 1.0 Univeral Public Domain Dedication** license has been written for the purpose of placing a work in the public domain, to the extent permitted by law.
As writen here:
https://github.com/nothings/stb/blob/8b5f1f37b5b75829fc72d38e7b5d4bcbf8a26d55/docs/why_public_domain.md?plain=1#L114-L116

The License combo you wrote has little legal value, and corporations might refrain from using your software because of that.
Using a license carefully crafted for dealing with ambiguity and jurisdiction issues depending on the state or region the user might live in will solve many issues, and will reassure most.

You can read here a short description of what this license does:
- https://creativecommons.org/share-your-work/public-domain/cc0
- https://creativecommons.org/publicdomain/zero/1.0/

Thank you for your libs, by the way.

**Comment by nothings** [comment]
The dual license was added explicitly because some lawyers were unhappy with public domain. It is impossible to please all lawyers, so no further changes to be licensing will be made to make lawyers happy.

**Comment by musicinmybrain** [comment]
It seems to me that lawyers unhappy with the Unlicense will just insist on using the software under the MIT license; the two licenses are conjoined with OR rather than AND, after all. While the MIT license is not public domain equivalent, it is probably the most popular permissive license in the world, so there ought to be very few lawyers dissatisfied.

Anyway, Fedora Linux [recently announced](https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/RRYM3CLYJYW64VSQIXY6IF3TCDZGS6LM/) that CC0 would no longer be an acceptable license for code (only allowed for content) due to the explicit "no patent license" clause it contains. Relicensing stb to CC0 would have been painful for Fedora packagers, who would have had to omit software that uses stb libraries or stick to old versions of the libraries.

I appreciate the decision to leave the current license terms intact.

**Comment by aviallon** [comment]
Allright. Some lawyers want liability it seems...
