### ISSUE TITLE
stb_image in CLI project throws linker errors

### ISSUE THREAD

**Issue by Ryder17z** [nothings/stb#1407]
**Describe the bug**
stb_image in CLI project throws linker errors 2019, 1120

**To Reproduce**
Add to CLI project, watch it fail with liker errors

**Expected behavior**
most, if not all functionality supported 

**Screenshots**
N/A

**Comment by N-R-K** [comment]
It would be more useful if you showed the linker error. But going by guess, you're most likely missing `-l m` to link the math library.

**Comment by Ryder17z** [comment]
I don't see where to add that for vs2022

**Comment by rygorous** [comment]
No actual repro nor an error message provided after 2 months, can't help with this issue if we don't get any information.

**Comment by Ryder17z** [comment]
It boils down to wanting to compile only as a part of a GUI application.
2019, 1120 are classic generic errors.

**Comment by rygorous** [comment]
You need to give us an actual repro and actual error messages. 2019 is "missing external symbol" and 1120 is "there were unresolved external symbols". Without the symbol names it could be literally anything.

We're compiling with Visual Studio as part of our development process all the time, as does a large number of users of stb_image, so I can guarantee the problem is on your end, but if you want us to help you debug this you need to give us _something_ more detailed than "it doesn't work".

**Comment by Ryder17z** [comment]
I can't do that right now, but I will dig deeper when I get time to do so
