### ISSUE TITLE
[stb_truetype] Division by zero in stbtt__new_active

### ISSUE THREAD

**Issue by heuripedes** [nothings/stb#149]
In `stbtt__new_active()`, `dxdy` is zero and causes a division by zero in line 1680:
```c
   float dxdy = (e->x1 - e->x0) / (e->y1 - e->y0);
   //STBTT_assert(e->y0 <= start_point);
   if (!z) return z;
   z->fdx = dxdy;
   z->fdy = (1/dxdy);
```

I dumped the operands of the previous division (http://pastebin.com/Pd7rbV46) and it seems `e->x1` and `e->x0` always have the same value.

Snipped of the code used to reproduce: (full code with embedded font at https://fuwa.se/onql0q.c)
```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#define STB_TRUETYPE_IMPLEMENTATION
#define STB_RECT_PACK_IMPLEMENTATION
#define STBTT_RASTERIZER_VERSION 2
#include "stb_rect_pack.h"
#include "stb_truetype.h"

unsigned char DroidSansMono_ttf[];

int main(int argc, char **argv)
{
	stbtt_pack_context pc;
	stbtt_packedchar   cd[256];
	unsigned char      atlas[1024 * 1024];

	memset(&pc,   0, sizeof(pc));
	memset(cd,    0, sizeof(cd));
	memset(atlas, 0, sizeof(atlas));

	stbtt_PackBegin(&pc, atlas, 1024, 1024, 1024, 1, NULL);
	stbtt_PackFontRange(&pc, DroidSansMono_ttf, 0, 32.0, 0, 256, cd);
	stbtt_PackEnd(&pc);

	return 0;
}
```

Font file: https://fuwa.se/87hyfg.ttf

**Comment by nothings** [comment]
Whoops, I missed investigating this bug in today's pass through stb_truetype.

**Comment by nothings** [comment]
The current version doesn't crash for me with my compiler. Note though that the current version, ranges starting with Unicode char 0 are broken; I'll post a fix to that as well.

Anyway, it's pretty clear what the bug is, so I attempted to fix it for the next version (and another related bug where it looked to me like the initial dxdy calculation could divide by 0, although I don't have a test case for it so maybe it's not possible for some other reason).
