### ISSUE TITLE
stb_truetype.h 1.06 assert with new rasterizer

### ISSUE THREAD

**Issue by ocornut** [nothings/stb#151]
( Passed on from this bug https://github.com/ocornut/imgui/issues/280 )

Using this font (it is an icon font) 
http://fortawesome.github.io/Font-Awesome/

Based on test_truetype.c this is making me assert:
(missing bits, as a hastily pasted chunks of test_truetype.c in my codebase)

```cpp
    fread(ttf_buffer, 1, 1<<25, fopen(argc > 3 ? argv[3] : "../../extra_fonts/fontawesome-webfont.ttf", "rb"));//c:/windows/fonts/mingliu.ttc", "rb"));

    {
        stbtt_pack_context pc;
        stbtt_PackBegin(&pc, temp_bitmap[0], BITMAP_W, BITMAP_H, 0, 1, NULL);
        stbtt_PackFontRange(&pc, ttf_buffer, 0, 20.0, 0xf000, 0x239, pdata);
        stbtt_PackEnd(&pc);
        stbi_write_png("fonttest2.png", BITMAP_W, BITMAP_H, 1, temp_bitmap, 0);
    }
```

I get an assert in stbtt__handle_clipped_edge() 
```cpp
      assert(x1 >= x && x1 <= x+1);
```

When trying to make a repro by tweaking character ranges I had the assert on different codepoint so it may be be tied to one specific codepoint/glyph.

it doesn't happen with #define STBTT_RASTERIZER_VERSION 1

**Comment by nothings** [comment]
I probably won't be able to get to this bug this weekend, so you might want to just enable VERSION=1 for a while.

**Comment by ocornut** [comment]
Thank you again, and needless to say no hurry. It's a pretty edgy case and we have a workaround.

**Comment by nothings** [comment]
The effect on the actual (non-assert) code appears to just be to add an epsilon to the AA coverage, so I'm *pretty* sure I could have just added an epsilon check to the assert to suppress it.

But instead I totally rewrote the calling code to have a ton more if()s to try to avoid having the epsilon, just in case there's something subtler that I'm missing; since this is part of the (hopefully rarely-exercised) brute forth path, the extra slowdown from the extra if()s shouldn't matter. Checking in the fix soon.
