### ISSUE TITLE
Consider clarifying which juristiction's definition of Public Domain you want to use, or use Creative Commons CC0 licence

### ISSUE THREAD

**Issue by AnyOldName3** [nothings/stb#1519]
**Is your feature request related to a problem? Please describe.**
Some countries use their own definition of *public domain* that's incompatible with that of the rest of the world. For example, in France, when something's in the public domain, its authors 'moral rights' must still be upheld, allowing the author to prohibit derivative works or withdraw the work, and requiring anyone using the work to include attribution. This can cause problems if you live in such a country, or move to one, or you die and one of your descendants lives there, and someone claims that territory's definition should apply.

**Describe the solution you'd like**
One option is to explicitly say where you live, and that you want that place's definition to be used, unless you're somewhere with a weird definition and don't like it. As an alternative, Creative Commons created the CC0 licence, which basically puts the common understanding of public domain into the necessary legalese to make it work around the world.

**Describe alternatives you've considered**
It would be a violation of international law to remove France from the world.

**Additional context**
N/A

**Comment by musicinmybrain** [comment]
As far as I can tell, the [current license](https://github.com/nothings/stb/blob/5736b15f7ea0ffb08dd38af21067c314d6a3aae9/LICENSE) is, in SPDX terms, `(`[`MIT`](https://spdx.org/licenses/MIT.html)` OR `[`Unlicense`](https://spdx.org/licenses/Unlicense.html)`)`. That’s quite different from a generic public-domain dedication.

**Comment by nothings** [comment]
Before 2011, CC0 was not acceptable for software, and many of the stb libs predate 2011. Even after 2011, the CC FAQ continues to recommend against using CC licenses for software.

Because the license has been endlessly complained about by various parties, it is clear there is NO LICENSE that can actually satisfy everyone in the world.

For this reason we settled some time ago on licensing every library under both MIT and Unlicense (public domain).

We're done. Because it is clear there is NO LICENSE that can actually satisfy everyone in the world, we're not going to change it anymore. It's done. It's over. No more. Stop asking for changes to the license.

**Comment by musicinmybrain** [comment]
> Before 2011, CC0 was not acceptable for software, and many of the stb libs predate 2011. Even after 2011, the CC FAQ continues to recommend against using CC licenses for software.

The following is mostly for the benefit of others who might be influenced by the discussion here.

In Fedora Linux, CC0 is now allowed only for content, [not for code](https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/RRYM3CLYJYW64VSQIXY6IF3TCDZGS6LM/), with exceptions for software already in the distribution, due to concerns about the language around patents. Fedora does accept public-domain dedications, and is not generally in the habit of disallowing licenses without good reason. I wouldn’t recommend any projects switch to CC0 for software licensing at this point.

The most widely accepted ultra-permissive licenses seem to be `MIT-0`, `0BSD`, and the `Unlicense`. Some corporations allow only some of these, and the first two are now more fashionable, but all three seem to be unproblematic for most users.

**Comment by AnyOldName3** [comment]
The Unlicense works, too. It's not mentioned in the readme, though, so I'd suggest doing that.
