### ISSUE TITLE
stb_image; potential tga info vs load bug

### ISSUE THREAD

**Issue by underscorediscovery** [nothings/stb#159]
I wrote a simple test of a binding for stb_image, and stumbled on the following behaviour.
Note that **the code path for reading the files and the `info` vs `load` calls are the same for each file.**

```
INFO:  image.png 4 x 1 comp:3
DATA:  image.png 4 x 1 comp:4 req_comp:4 / 16 bytes

INFO:  image.gif 4 x 1 comp:4
DATA:  image.gif 4 x 1 comp:4 req_comp:4 / 16 bytes

INFO:  image.jpg 4 x 1 comp:3
DATA:  image.jpg 4 x 1 comp:3 req_comp:3 / 12 bytes

INFO:  image.bmp 4 x 1 comp:3
DATA:  image.bmp 4 x 1 comp:3 req_comp:3 / 12 bytes

INFO:  image.psd 4 x 1 comp:4
DATA:  image.psd 4 x 1 comp:4 req_comp:4 / 16 bytes
```

But here's the interesting one:

```
FAIL: INFO: image.tga / Image not of any known type, or corrupt
DATA:  image.tga 4 x 1 comp:3 req_comp:3 / 12 bytes
```

I defined `STBI_FAILURE_USERMSG`, and the above error is listed, but only for the `info` call.

The `info` call looks (as you'd expect) like this:
```cpp
int w = 0;
int h = 0;
int comp = 0;
int res = stbi_info(filename, &w, &h, &comp);
```

The `data` call looks like this:
```cpp
int w = 0;
int h = 0;
int comp = 0;
unsigned char* image_bytes = stbi_load(filename, &w, &h, &comp, req_comp);
```

Here is the image.tga in question.
http://underscorediscovery.com/sven/image.tga

I haven't had time to debug it directly just yet, 
but figured I would make a note here in the mean time to remind me.

**Comment by nothings** [comment]
I'll take a look at it next time I take a pass at stb_image.

**Comment by nothings** [comment]
Fixed this. There were three bugs:

1. PIC info checker checks for EOF after 92 bytes, but fails to rewind the file there, breaking the next checker

2. If EOF was reached, the file could no longer be rewound at all (due to the system for keeping track of our own buffer and the hacky implementation of rewind)

3. PIC info checker had this behavior but PIC load checker didn't have this behavior because PIC info checker was missing the initial test of the first 4 bytes, relying only on testing some later bytes

All of these are fixed.

**Comment by underscorediscovery** [comment]
Looks good from here, thanks!

```
INFO: image.tga 4 x 1 comp:3
DATA: image.tga 4 x 1 comp:3 req_comp:3 / 12 bytes
```
