### ISSUE TITLE
Array Out Of Bounds - stb_image_resize2.h

### ISSUE THREAD

**Issue by ThatOSDev** [nothings/stb#1616]
**Describe the bug**
 Lines 8510, 8611, and 8702 show the same code used, and each line causes an Out Of Bounds warning in GCC 11.2.
 The filename is stb_image_resize2.h
 GCC 11.2 with c17.

```c
stbir_uint32 const * to_srgb = fp32_to_srgb8_tab4 - (127-13)*8;
```

It will SPAM you with the same array warning for each one of the three lines listed above. This below is just one of hundreds of spam-like examples of the warning.
```
libs\raylib-master\src\external\stb_image_resize2.h|1129|note: while referencing 'fp32_to_srgb8_tab4'|
libs\raylib-master\src\external\stb_image_resize2.h|8702|warning: array subscript -912 is outside array bounds of 'stbir_uint32[104]' {aka 'unsigned int[104]'} [-Warray-bounds]|
```

I edited the beginning of the path to libs / raylib to keep it simpler to read. However, this is not about raylib, but about the warning generated from stb_image_resize2.h.

SIDE NOTE :  I have tested this in the new raylib 5.0. It's using the same file (stb_image_resize2.h) from the original stb github. So you can easily reproduce this warning by compiling the raylib code if that makes it easier to spot. The warning always comes from those lines in stb_image_resize2.h.

**Comment by nothings** [comment]
As far as I can tell, you have to enable this warning explicitly, or use `-Wall`. We don't generally fix `-Wall`-only warnings.

Because you're meant to compile the project into your source code with your own compiler settings, we do try to eliminate warnings in general, but warnings from `-Wall` are generally too numerous, too marginal, or too inconsistent.

**Comment by ThatOSDev** [comment]
> As far as I can tell, you have to enable this warning explicitly, or use `-Wall`. We don't generally fix `-Wall`-only warnings.
> 
--SNIP--

I should have added my settings...  Here is what I use in my makefile.

CFLAGS=-Wall -Werror -std=c17 -m64 -O2 

From what I am seeing, the function is trying to run math on an array table "fp32_to_srgb8_tab4". And this is why it's showing an Out Of Bounds warning.

I did succeed in removing the warning once, when I removed the const pointer. But I'm not sure if that was the right thing to do. Either way, I was told to mention this warning here from the raylib discord, since raylib 5.0 is using the stb_image_resize2.h header file. In raylib 4.x it was using the first iteration "stb_image_resize.h". It was fine with no errors. But version 2 seems to have a lot of issues. I only listed just one of them here on this thread.

I'll post if I find a fix for this. Thanks for replying. Cheers

**Comment by jeffrbig2** [comment]
I can post a fix for this one - like Sean said we don't normally worry about -Wall, but I can tweak the code easily enough to avoid the GCC warning easily enough. It does not read outside the buffer, of course - it's just an, in this case, unhelpful warning.

**Comment by ThatOSDev** [comment]
> I can post a fix for this one - like Sean said we don't normally worry about -Wall, but I can tweak the code easily enough to avoid the GCC warning easily enough. It does not read outside the buffer, of course - it's just an, in this case, unhelpful warning.


That would be great Jeff. Thank you.

Side Note : If this was one or two warnings, I wouldn't bother you all with it. But this spams 163 Warnings all for that same thing. So the Fix will be MUCH appreciated. Cheers.

**Comment by jeffrbig2** [comment]
No prob!

Remember you can do:

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Warray-bounds"
#include "stb_image_resize2.h"
#pragma GCC diagnostic pop

In the meantime...

**Comment by ThatOSDev** [comment]
> No prob!
> 
> Remember you can do:
> 
> #pragma GCC diagnostic push #pragma GCC diagnostic ignored "-Warray-bounds" #include "stb_image_resize2.h" #pragma GCC diagnostic pop
> 
> In the meantime...

That supression trick comes in handy. Thank you for the feedback. Cheers

**Comment by tcauchois** [comment]
Hi all,

I just wanted to add that this same warning has caused us some trouble as well in OpenUSD.  If anyone has a fix already, it would be great to see that merged, or at least I could add it as a patch in my build.

Thanks!

**Comment by nothings** [comment]
Because it seems to be a workaround for a compiler bug, not a fix for a library bug, I'm not considering it high priority. It'll get fixed at some point, but no rush.

**Comment by jeffrbig2** [comment]
I just posted the next version that fixes this, but remember you can easily wrap the header to avoid this (see two messages above)...

**Comment by ThatOSDev** [comment]
> I just posted the next version that fixes this, but remember you can easily wrap the header to avoid this (see two messages above)...

I went looking for the posted version you mention, but github shows that the stb repo hasn't been updated for 3 months. Did I miss something ?

**Comment by nothings** [comment]
I have merged Jeff's new version to the repo. Looking at the code I'm not sure how this would fix the warning, let me know if it doesn't and I'll reopen.

**Comment by jeffrbig2** [comment]
I may still have to roll the negative into the index, but this silenced on my mingw...

  -Jeff

**Comment by tcauchois** [comment]
Works great for me.  Thanks so much!

**Comment by gregjotau** [comment]
This still trips UBSan in the current header (`stb_image_resize2` v2.18 at commit `2c980bb59875b0d32144a71867fbdebb2f77cd20`):

```text
stb_image_resize2.h:8835:7: runtime error: index -912 out of bounds for type 'const stbir_uint32[104]'
```

The eventual lookup address is within the table, but forming `fp32_to_srgb8_tab4 - 912` is itself undefined pointer arithmetic in C. Suppressing `-Warray-bounds` therefore does not address the UBSan error.

We fixed it downstream by passing the real table base and subtracting the same offset from each integer lookup index. This preserves the SIMD path and produces identical table accesses/output without forming a pointer before the array:

https://github.com/beint-no/glimt/blob/v0.2.0/native/patches/stb/0001-defined-srgb-simd-table-lookup.patch

The patched header passes our Linux ASan/UBSan resize matrix across 8/16-bit, opaque/alpha, four filters, and twelve dimension pairs. I am adding this here because it is the same underlying report and the earlier change only moved the invalid pointer formation into the SIMD call sites.
