### ISSUE TITLE
Sprite padding

### ISSUE THREAD

**Issue by 1vanK** [nothings/stb#1686]
Please add the ability to expand a image by a certain number of pixels with copies of the outer pixels of this image. This is necessary to get rid of seams when using texture atlases.

https://www.youtube.com/watch?v=pXc-H0pb668&t=47s
http://www.imagemagick.org/discourse-server/viewtopic.php?t=34525
https://tiled2unity.readthedocs.io/en/latest/fixing-seams/

![](https://tiled2unity.readthedocs.io/en/latest/img/rygar-tile-16x16.png)
![](https://tiled2unity.readthedocs.io/en/latest/img/rygar-tile-18x18.png)

**Comment by nothings** [comment]
This repo contains multiple libraries, you'll have to say which one you mean.

Why is the thing you're talking about the reponsibility of the stb library? If the behavior is specific to texture atlases, shouldn't the library or tool that's packing the textures together be responsible for adding needed padding data?

**Comment by nothings** [comment]
Also, for sprite atlases of pixel-art, where you're going to nearest-neighbor sample, the correct solution is NOT to weirdly expand the texture with unnecessary data, it's to use a shader that clamps to the tile, or, if that's too much work, a very slightly contracted set of texture coordinates. E.g. try moving the corners of the rectangle's texture coordinates inwards by 1/256th of a texel (or maybe slightly more, 3/256ths, to be on the safe side).

**Comment by 1vanK** [comment]
> This repo contains multiple libraries, you'll have to say which one you mean.

additional function in image_resize, i think

**Comment by 1vanK** [comment]
> Also, re: that third link, for sprite atlases of pixel-art, where you're going to nearest-neighbor sample, the correct solution is NOT to weirdly expand the texture with unnecessary data, it's to use a shader that clamps to the tile,

I don't quite understand how you are going to deal with trilinear filtering and msaa in the shader. And with non-integer sprite coordinates, even GL_NEAREST does not always save from using neighboring texels.

> E.g. try moving the corners of the rectangle's texture coordinates inwards by 1/256th of a texel (or maybe slightly more, 3/256ths, to be on the safe side).

This causes the sprite to blur.

**Comment by 1vanK** [comment]
Unity uses this way

**Comment by 1vanK** [comment]
![1](https://github.com/user-attachments/assets/465a0d40-dc42-493c-9ef3-5580f1a1d3b4)

**Comment by nothings** [comment]
Ok, two topics: 1, your request for stb_image resize, and 2, the aside about pixel art:

1.

What? No, that doesn't make any sense. Producing output padding during a resize operation is silly.

When resampling, resize can do clamp-to-edge or wrap for the texels *it* samples, but it makes absolutely no sense to produce anything else. If you want padded output, you can pad it yourself, but that's not a normal thing to want, and I don't understand how this has anything to do with texture atlases. Do you want padding when resizing texture atlases? Sure. But that's got to be done to the source image before calling stb_image_resize.

2.

None of your replies account for the fact that I said 
>pixel-art, where you're going to nearest-neighbor sample

If you're not nearest-neighbor sampling, then all bets are off (but using a pixel shader still works). My reply only pertained to nearest-neighbor (GL_NEAREST). Because I said that. Because I prefaced my comments with that. So taking them out of context and criticizing them doesn't make any sense.

**Comment by 1vanK** [comment]
I'm just making a utility that loads a tileset of individual tiles, expands them, and packages them into an atlas. So I thought it would be nice to have an image expansion feature in your library.

**Comment by nothings** [comment]
Why do you want a random library to do a random thing? Should it also load tiles from individual files. Should it package them into an atlas? I don't understand why you think this "expansion" is an appropriate behavior for this library.

**Comment by 1vanK** [comment]
Well, I'm not trying to convince you of anything. I understood from your Twitter what kind of character you are.
