### ISSUE TITLE
stb_truetype bug passing the allocation context to STBTT_malloc

### ISSUE THREAD

**Issue by 4th-dimention** [nothings/stb#213]
Calls to stbtt_PackFontRanges and stbtt_BakeFontBitmap can lead to calls to STBTT_malloc (and presumably STBTT_free) where the void* parameter, the "alloc_context", comes from the uninitialized userdata member of stbtt_fontinfo.

In stbtt_PackFontRanges the issue is easy to fix by adding:
info.userdata = spc->user_allocator_context;
Before the call to stbtt_InitFont

The problem is less easily solved for stbtt_BakeFontBitmap because there is no parameter in that function for passing the "alloc_context".

**Comment by nothings** [comment]
I'll fix this for the next version.

The fact that stbtt_BakeFontBitmap doesn't support the allocation context is a known issue which is why a new baking API that *does* support it was added, and the old baking API is left not supporting it intentionally (and hence it doesn't use the new reactangle stuff).

**Comment by nothings** [comment]
Should be fixed, but untested.
