### ISSUE TITLE
packing for use in clib

### ISSUE THREAD

**Issue by nothings** [nothings/stb#247]
@erf wrote: 

Would it be an idea to split those up and add them as micro libraries to clibs ?

Split up stb libraries into separate repos with a package.json, so that they are easy to search for and add to projects via clibs.

**Comment by nothings** [comment]
Anyone else is welcome to do so (they're public domain, so rock on), but I don't use clib or know anyone who uses it, so not worth my time.

**Comment by erf** [comment]
Thanks! Not to start a discussion or anything but I'm watching your [Advice for Writing Small Programs in C video](https://www.youtube.com/watch?v=eAhWIO1Ra6M). You mention **code-reuse**, and I believe packet managers like [clib](https://github.com/clibs/clib) can help with that (at least if you want to share code with other people). I think alot of the popularity with [node.js](https://nodejs.org/), is because of its packet manager [npm](http://npmjs.com) - also [gradle](http://gradle.org) and [cocoapods](https://cocoapods.org/) helps developers being more productive. I believe a packet manager for c would help with the lacking standard library and make it easier for more people to start using the language. I think [clib](https://github.com/clibs/clib) looks promising and i hope more people start sharing their code there.

**Comment by erf** [comment]
I've created a [repo](https://github.com/clibs/clib/) for [stb.h](https://github.com/nothings/stb/blob/master/stb.h) and added it to [clib](https://github.com/clibs/clib/)'s Wiki. 
Now you can install `stb` with `clib install erf/stb` and search for it with `clib search stb`. (-c to skip cache).

**Comment by nothings** [comment]
Given the recent npm "left-pad" incident I'm pretty suspicious of the idea of a package manager for small functions, but in this case it's still out of my hands, so do as you will!
