### ISSUE TITLE
stb_vorbis sanity check prevents file from being played

### ISSUE THREAD

**Issue by sagamusix** [nothings/stb#259]
Here's a vorbis file that seems to play fine in pretty much any player I tried: http://sagagames.de/stuff/resopad.ogg

However, when using stb_vorbis in pushdata mode, it seems to bail out early because it doesn't like something about the file:
When calling `is_whole_packet_present`, it trips over this condition: `if (s < f->segment_count-1)             return error(f, VORBIS_invalid_stream);`
So maybe this sanity check can be loosened / corrected?

**Comment by nothings** [comment]
I'll have to check if it works in pulldata mode. I glanced over the spec and can't tell what rule it's trying to enforce there.

**Comment by nothings** [comment]
Fixed in next version.

**Comment by nothings** [comment]
I've backed out this fix as I hadn't sufficiently tested it. As discussed in #274, the following things are true:

- the "fix" breaks other file
- ogginfo reports the file as being invalidly formatted

So it is true that other players play this, and stb_vorbis could probably be fixed to handle it instead of refusing due to the invalid formatting, but I don't have the willpower to try to figure out the safe fix right now, and historically the stb libraries have had the attitude of "fix your file if it's broken".

So I'm going to let this stand as is, although if someone wants to fix it I'll be happy to integrate the fix. Issue #274 proposes a possible fix, but testing is needed to be sure it works (and doesn't break anything else).
