### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [nothings/stb#277]
I would like to point out that identifiers like "[`stb__perlin_randtab`](https://github.com/nothings/stb/blob/ee6978cb6891632e3fe84264f832140e590b43f0/stb_perlin.h#L48)" and "[`stbi__context`](https://github.com/nothings/stb/blob/fdca443892d0ce3c8680e6f38f196c61e95c7de3/stb_image.h#L742)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to [adjust your selection for unique names](https://github.com/nothings/stb/blob/ee6978cb6891632e3fe84264f832140e590b43f0/docs/stb_howto.txt#L93 "Update candidate")?

**Comment by zao** [comment]
Is there an actual collision you've observed in the wild or an implementation that uses similar prefixes that is at risk of collision.
Some things are more important to conform to than others, and the extremely wide "double underspaces are forbidden" rule is one that really shouldn't exist in the form it currently does.

If you're out to burn months of programmer attention by reporting non-issues to issue trackers, can't you at least pick an issue that has a chance of actually mattering?

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by zao** [comment]
In C, it does not use any reserved identifiers.
In C++, that's the problem of the integrator if they decide to compile the TU with `STB_IMAGE_IMPLEMENTATION` and `STB_PERLIN_IMPLEMENTATION` as C++ instead of C.
If you're not familiar with the stb libraries, you define the implementation macro in a single TU, which traditionally is built as a C file as that's what it is.

It's a non-problem as no C reserved identifiers are used, and in C++, if you call this "undefined behaviour" worth caring about, you need a real hobby. No-one is going to summon nasal daemons from the presence of an identifier that has two underscores in the middle.

I know that you are not possible to reason with from previous experience with your carpet bombing, I'm just providing an argument for with which to rapidly close this pointless issue.

**Comment by nothings** [comment]
>Would you like to adjust your selection for unique names?

No. As noted elsewhere, I am fully aware of the theoretical issue (https://github.com/nothings/stb/blob/master/docs/stb_howto.txt#L113). If this becomes a practical rather than theoretical issue, it can be addressed when that happens.

>How do you think about to avoid that this software depends on undefined behaviour?

I think compilers that exploit undefined behavior for optimization are broken, as are standards that encourage this; the de facto standard has historically been otherwise, and we shouldn't encourage compilers to deviate from the de facto standard. (Indeed, At least one stb library is explicitly reliant on disabling strict-aliasing optimizations, i.e. it 'depends on undefined behavior'.)

**Comment by elfring** [comment]
>… If this becomes a practical rather than theoretical issue, …

* Do you care if your source code tampers with the reserved C++ name space?
* Is it harder to achieve consensus on the consequences for the term "undefined behaviour"?

**Comment by RichardGale** [comment]
My app shipped successfully in all app stores so I for one don't care about the odd underscore.

**Comment by rygorous** [comment]
Please, everyone, this isn't a forum, it's a bug tracker. Keep it focused
and don't trade insults.

As Lars correctly pointed out, this is a C++ restriction and the stb libs
are written in C. C++ compatibility is generally maintained but is not a
must, and some of the libs in this repository already don't work in C++,
e.g. stretchy buffer.

If this ever causes anyone actual problems, it will get changed. As-is,
this ranks at about the same level of importance as compatibility issues
with platforms having one's complement integers or non-8-bit-bytes, namely:
entirely hypothetical for the users of these libraries (so far).

As a general rule, the stb libraries (and their existing users) care a lot
more about practical compatibility with actual compilers (including several
embedded or old compilers that diverge from the C/C++ standards in various
ways) than they care about language lawyering.

**Comment by nothings** [comment]
Actually all stb-prefixed libraries are supposed to be fully C++ compatible.


>Do you care if your source code tampers with the reserved C++ name space?

No. All further questions you ask along these lines will be answered with "no", so you can stop asking them.

>Is it harder to achieve consensus on the consequences for the term "undefined behaviour"?

I have the consensus of my peers and my users.

http://blog.regehr.org/archives/1180
http://robertoconcerto.blogspot.com/2010/10/strict-aliasing.html
https://lkml.org/lkml/2003/2/26/158

I don't care about the opinions of language lawyers, compiler writers, or standards authors.
