### ISSUE TITLE
Optimized stb_vorbis::ilog

### ISSUE THREAD

**Issue by technosaurus** [nothings/stb#289]
ilog() had an [Optimize me comment](https://github.com/nothings/stb/blob/4c519106a7c3862524100f907736c1c74412725d/stb_vorbis.c#L980) so I thought I would submit this (may need more ifdef-ing for obscure compilers)

``` c
int ilog(int x){
#ifdef _MSC_VER
    unsigned long ret = 0;
    _BitScanReverse( &ret, x );
    return ret;
#else //gcc, clang and icc all have this:
    return 32 - __builtin_clz(x);
/////
//  my alternative method is also public domain
//  see: http://codegolf.stackexchange.com/a/35211/21288
//  it boils down to this
//  int i=(sizeof(x)*8), r=-!x;
//  while(i>>=1) x>>i ? x>>=i , r+=i: 0;
//  return r;
////
#endif

}
```

This is similar to the [fast inverse square root](https://en.wikipedia.org/wiki/Fast_inverse_square_root) problem, but that method depends on a specific floating point format.

**Comment by darkuranium** [comment]
I'd personally change that `#else` to `#elif defined(__GNUC__)` and the likes. Then leave *another* `#else` with the old code for better portability.

Basically:

```c
static int ilog(int32 x)
{
#ifdef _MSC_VER
    unsigned long ret = 0;
    _BitScanReverse(&ret, x);
    return ret;
// ICC and clang both define this, too! If you're paranoid, there's always __INTEL_COMPILER
// and __clang__, though (but they're unnecessary). CLang also has the more appropriate
// `__has_builtin(__builtin_clz)`, which is more robust w.r.t. systems without that builtin.
#elif defined(__GNUC__)
    return 32 - __builtin_clz(x);
#else
    /*... "manual" (old) code ...*/
#endif
}
```

**Comment by eloj** [comment]
Maybe add an assert that x > 0.

**Comment by rygorous** [comment]
Support for x <= 0 (and returning 0 in that case) is a normative requirement in the Vorbis spec. https://xiph.org/vorbis/doc/Vorbis_I_spec.html#x1-1190009.2.1

As of commit 66fdbaaa87, the fix for that being handled incorrectly is in. The "optimize" comment is a red herring - as per profiling, stb_vorbis spends no appreciable amount of time there at all. Definitely not worth pulling in random platform dependencies for. I'm closing this issue. :)
