### ISSUE TITLE
stb.h: stb_filewrite of 64MB files

### ISSUE THREAD

**Issue by nothings** [nothings/stb#304]
Need to stream out smaller buffers at a time due to this Windows bug: https://support.microsoft.com/en-us/kb/899149

**Comment by haikarainen** [comment]
Citing the link you posted:

>To work around this problem, use one of the following methods:
1. **When you open a file, use the w+b (reading and writing) access type as the mode parameter.**
2. Use a smaller buffer. Then, call the fwrite function in a loop until you write the number of bytes that you want to the file.

It looks like you just need to open with `w+b` instead of `wb` (as it is currently). In other words, doesn't seem to be a need for smaller buffers. Just wanted to point that out so you don't miss it.

**Comment by rygorous** [comment]
This was fixed in commit 4806aca183000a472e621388f15cc907f4caeac.
