### ISSUE TITLE
stb_truetype: Can't load Inconsolata.otf

### ISSUE THREAD

**Issue by tn0502** [nothings/stb#340]
It seems `Inconsolata.otf` is missing some tables that is required by `stb_truetype`. Is this a limitation in the library or is the font at fault? If the former, how difficult would it be to add support for these OTFs?

The font can be downloaded from [here](http://www.levien.com/type/myfonts/inconsolata.html).

```
Process 56416 stopped
* thread #1: tid = 0x8e551, 0x0000000100678e33 rainbow`stb::stbtt_InitFont(info=0x0000000102abe820, data2="OTTO", fontstart=0) + 675 at stb_truetype.h:1043, queue = 'com.apple.main-thread', stop reason = step over
    frame #0: 0x0000000100678e33 rainbow`stb::stbtt_InitFont(info=0x0000000102abe820, data2="OTTO", fontstart=0) + 675 at stb_truetype.h:1043
   1040    info->hmtx = stbtt__find_table(data, fontstart, "hmtx"); // required
   1041    info->kern = stbtt__find_table(data, fontstart, "kern"); // not required
   1042    if (!cmap || !info->loca || !info->head || !info->glyf || !info->hhea || !info->hmtx)
-> 1043       return 0;
   1044
   1045    t = stbtt__find_table(data, fontstart, "maxp");
   1046    if (t)
(lldb) p cmap
(stb::stbtt_uint32) $8 = 1324
(lldb) p *info
(stbtt_fontinfo) $10 = {
  userdata = 0x0000000000000000
  data = 0x0000000105290400 "OTTO"
  fontstart = 0
  numGlyphs = 0
  loca = 0
  head = 188
  glyf = 0
  hhea = 244
  hmtx = 57056
  kern = 0
  index_map = 0
  indexToLocFormat = 0
}
```

**Comment by nothings** [comment]
OpenType is a superset of TrueType, so it may just not be a TrueType font. That would be my guess without looking into it further.

**Comment by rygorous** [comment]
Inconsolata is an OpenType font with Type1 outlines, not TrueType outlines (and no "glyf" table). So yeah, not supported.

Type1 is a completely separate outline format using its own file format (CFF) which gets embedded into OTFs as a container. It also uses different primitives (cubic Bezier curves instead of quadratic). Supporting it is a major effort (and doesn't easily admit using the uncompressed file data in-place, as TrueType does).

**Comment by nothings** [comment]
Should be addressed by https://github.com/nothings/stb/pull/361 whenever that gets merged, so I'm closing this now as a bit of housekeeping.

**Comment by tn0502** [comment]
Thanks. I'll have another look once it's merged.

**Comment by danielmaciel** [comment]
Hi! For some reason if I try to bake a bitmap using inconsolata.otf it produces an empty bitmap. The glyphs seem to be too large as stbtt_GetGlyphBitmapBox(...) sets x1 and y1 to huge values.

**Comment by nothings** [comment]
But the same code works for other fonts?

**Comment by dougallj** [comment]
Yeah, there's a bug somewhere here, sorry. A quick hack to make it work is truncating the arguments to `stbtt__track_vertex`:

`static void stbtt__track_vertex(stbtt__csctx *c, stbtt_vertex_type x, stbtt_vertex_type y)`

I'm guessing some of the charstring operations deliberately overflow, which a true 16.16 fixed-point implementation would handle as expected. But my float implementation fails to wrap, and then it just gets truncated because `stbtt_vertex_type` is `short`?

It's not such a bad hack, but I think it indicates we're losing a few bits of precision unnecessarily. Sorry. I'll look at better options for fixing it if I get a chance, but that's what I've figured out so far if anyone else wants to look at it first.

**Comment by dougallj** [comment]
I think the actual bug is:

```
f = (float)stbtt__buf_get32(&b) / 0x10000;
```

which should be
```
f = (float)(stbtt_int32)stbtt__buf_get32(&b) / 0x10000;
```

Oops.

**Comment by danielmaciel** [comment]
@nothings Yes it works for my other .OTF fonts.
@dougallj Thanks a lot man. I have actually downloaded 'inconsolata.ttf' instead of the .otf version. Seems like the .otf version is not the official release of said font.
