### ISSUE TITLE
SIGSEGV on stb_sdict_set()

### ISSUE THREAD

**Issue by rcarbone** [nothings/stb#346]
I fixed a segmentation violation in stb_sdict_set() which occasionally occured in my program. Valgrind suggested me a “conditional jump or move depends on uninitialized value(s)” .

My fix was to substitute the statement in stb.h at line 3888
TYPE _h = (TYPE *) malloc(sizeof(_h));
with
TYPE _h = (TYPE *) calloc(1, sizeof(_h));
in order to allocate memory all inizialized to \0

ciao
/rocco

**Comment by nothings** [comment]
Are you initializing with stb_sdict_create instead of stb_sdict_new? Only the latter is correct. That's the only way I see to create an uninitialized value.

Here are the fields in the structure being malloced:
   void *arena; // FIELDS, specified at line 4258
  STB_(N,_hashpair) *table;
  unsigned int mask;
  int count, limit;
  int deleted;
  int delete_threshhold;
  int grow_threshhold;
  int shrink_threshhold;
  unsigned char alloced, has_empty, has_del;
  VALUE ev;
  VALUE dv;

Immediately after the malloc, 'init' is called, which initializes all of the above fields except 'arena', 'ev', and 'dv'. 'arena' is initialized as part of stb_sdict_new.  access to 'ev' and 'dv' are guarded by 'has_empty' and 'has_del'.

**Comment by rcarbone** [comment]
Hi Sean,
yes I used stb_sdict_create() but I will immediately change to stb_sdict_new() as suggested and post the result.

But I have another minor problem with stb_idict_set() (please note idict not sdict). I am trying to fix it just now,

It seems to me that the count field is not correctly updated after a call to stb_idict_set() and my simple test case attacched fails.

Last.
Have you considered to split the header file in several small files per argument? in a development environment it does matter. I am compiling and compiling several times and the compilation of a single file using stb.h takes so long to complete also for code I do not need.

in the zip file attacched there also the hacked version of stb.h in order to use only the hash table functions.

ciao
/rocco

[stb-simple-test.tar.gz](https://github.com/nothings/stb/files/418630/stb-simple-test.tar.gz)

**Comment by nothings** [comment]
The 'count' field in the dictionary data types is not a public field, it is private to the implementation. It stores the number of items stored in the actual hash array, but up to two items may not be stored in the array itself.

(This is because it is necessary to put special EMPTY and DELETED tokens in the hash table array, and the implementation reserves two of the possible keys to represent those values, thus those two keys cannot be stored in the array, and are stored specially. 'count' does not account for those two keys, as its purpose is to keep track of the array, not to tell the user how many items are stored in the hash table.)
