### ISSUE TITLE
stb_vorbis_decode_filename is slow with big ogg files

### ISSUE THREAD

**Issue by codz01** [nothings/stb#347]
Hi
stb_vorbis_decode_filename function decode the whole file which take long time especially with big ogg files .
is there some tricks to speed up the loading time ?

many thanks

**Comment by dougallj** [comment]
The first trick would be to not decode the whole file at once.

Assuming you don't want to do this, you might find that reading the whole file into memory and calling `stb_vorbis_decode_memory` is significantly faster. (There's a significant slowdown associated with calling `fgetc` for every byte in the file on some platforms, due to locking. @nothings: if you want to treat this as a real issue instead of a support request, this could be fixed in the same way as in `stb_image`)

Best of luck!

**Comment by codz01** [comment]
@dougallj , thanks for reply ,  i also tried stb_vorbis_decode_memory , it gives the same decoding time . 
how to decode only the section that is needed for playback during the next frame ?
