### ISSUE TITLE
Static analysis warnings in stb_image.h

### ISSUE THREAD

**Issue by seanmiddleditch** [nothings/stb#366]
```
g:\libs\libs\stb\stb_image.h(1894): warning C6011: Dereferencing NULL pointer 'data'. 
g:\libs\stb\stb_image.h(3412): warning C6001: Using uninitialized memory 'coutput'.
g:\libs\stb\stb_image.h(3438): warning C6262: Function uses '18316' bytes of stack:  exceeds /analyze:stacksize '16384'.  Consider moving some data to heap.
g:\libs\stb\stb_image.h(3740): warning C6001: Using uninitialized memory 'lencodes'.
g:\libs\stb\stb_image.h(3740): warning C6385: Reading invalid data from 'lencodes':  the readable size is '455' bytes, but '-1' bytes may be read.
```

The code is dense enough that it's difficult for me as a human unfamiliar with the code to see if any of these are serious safety problems. At least one looks like it might allow stack corruption from malformed input files, though. The others may be false positives but should still be cleaned up so that static analysis passes over codebases using stb doesn't spew noise.

I'd suggest adding `/analyze` (for Microsoft compilers) or using `scan-build`/`clang-analyze` (for Clang/GCC) to a CI setup for this project (using the free Appveyor and Travis CI services)..

**Comment by rygorous** [comment]
At least the coutput one was a real bug (albeit somewhat esoteric to trigger); I just ran `cl /analyze` on the current dev tree and found some issues. The stack size for the `stbi__gif` contexts has gotten worse and should probably be fixed at some point but that's a separate code quality issue and the GIF loader has more serious problems. Anyway, the coutput issued will be fixed in the next release.
