### ISSUE TITLE
Make stb_images thread safe

### ISSUE THREAD

**Issue by realitix** [nothings/stb#388]
Currently, `stbi__vertically_flip_on_load` is a global variable.
If I have 2 threads and that I want to load images flipped in one thread and not in the other, I can't.

Of course, it's a strange use case, but it could be needed.

What do you think about it ?

Jean-Sébastien

**Comment by nothings** [comment]
Is this something you actually need, or is it purely hypothetical?

There was previous discussion in https://github.com/nothings/stb/pull/89 which mentions multiple different strategies for addressing this, but at the time nobody actually needed it, it was purely hypothetical, so I didn't consider it worth spending time on.

Since that got closed when the initial fix went in, I'll leave this one open.

**Comment by realitix** [comment]
I don't need it and indeed it's purely hypothetical. I'm doing a 3D framework with Vulkan and I use your library to load image. I can't know what the developers will do with it.
From my point of view, it would be strange to do that. Maybe this very specific use case doesn't worse it.

We should wait a little for others opinions about it.

**Comment by darkuranium** [comment]
@realitix: I suppose a solution (or rather, workaround) for you would be to keep flipping disabled in `stb_image`, and instead do it manually, in your own code. Should be relatively simple, you just do swap pairs of `pitch = width * nchannels` elements (doing `height / 2` swaps).
