### ISSUE TITLE
stb_sprintf.h - snprintf and vsnprintf return value non-standard

### ISSUE THREAD

**Issue by eisbehr** [nothings/stb#408]
The return value in this implementation is the number of characters written to the buffer, and never more than n (the buffer size).
The typical behavior of snprintf and vsnprintf is to return 
> The number of characters that would have been written if n had been sufficiently large, not counting the terminating null character.

This can be used to pass 0 as the buffer pointer, 0 as the size, then the format string and arguments, to have the function return the length your buffer would have needed. Then you can allocate a buffer of that length and call it again with proper arguments.

If this behavior is not wanted for some reason (maybe speed?), the differing behavior should probably be noted.

**Comment by itamago** [comment]
Hello,
I am facing the same issue because standard usage would be in 3 steps : 
 - int size = vsnprintf(NULL, 0, ....) is firstly used to know how much buffer to allocate
 - char* buffer = new char[size+1] allocate the buffer to store the result
 - vsnprintf(buffer, size, ....) is then used to fill the buffer
As eisbehr pointed out, if this behaviour is not wanted, this difference from standard behaviour should be documented.
Thanks

**Comment by fahickman** [comment]
An alternative to returning the number of bytes that would have been written, less the nul terminator, is to return the number of bytes that were _left out_ due the buffer size. Since the only time the nul terminator would not be written is the zero-size buffer case, it would be included in that count. This means you wouldn't need the +1 when allocating space for the buffer after the call. (I hate having to deal with +/- 1s in string buffer code, so I structure all my string functions to avoid them.)

If the intent is for stb_sprintf to be a drop-in replacement for std snprintf, then mimicking the standard behavior is best, but I thought I'd mention this as a possible alternative.

**Comment by nothings** [comment]
Fixed in next version.
