### ISSUE TITLE
stb_truetype "randomly" crashes inside stbtt_FindGlyphIndex

### ISSUE THREAD

**Issue by jnsmalm** [nothings/stb#414]
My program uses stb_truetype for creating a texture with the glyph bitmaps. Sometimes it crashes, mostly inside stbtt_FindGlyphIndex (but sometimes in other places in stb_truetype.h as well). Sometimes it works without any changes to the program. The error message I get is:

    Assertion failed: (0), function stbtt_FindGlyphIndex, file ../deps/stb/stb_truetype.h, line 1417.

It also (strangely) seems like it's somehow connected to the number of rapid calls to stbtt_FindGlyphIndex. The more calls the program makes to stbtt_FindGlyphIndex, the chance of an error increases.

My platform is macOS 10.12

**Comment by rygorous** [comment]
Given the description of the bug, I'm almost certain this is not a bug in stb_truetype but in your code.

My guess is this: you're calling `stbtt_InitFont` and then freeing (or otherwise reusing) the memory you passed in as `data`. That is not allowed. You need to keep `data` around (along with your `stbtt_fontinfo`) for as long as you're using the font.

**Comment by rygorous** [comment]
I added the "documentation fix" label; not sure whether this is the bug or not, but the requirement for the buffer to stick around, while stated in the file (line 99), should be repeated in the comments for stbtt_InitFont.

**Comment by jnsmalm** [comment]
You where obviously correct. I'm using stb_truetype together with node.js and did not anticipate that the buffer would get freed by V8. Thanks for pointing me in the right direction.

**Comment by nothings** [comment]
Thanks for letting us know. Leaving this bug open until the doc fix goes in.
