### ISSUE TITLE
stb_truetype poor small size quality

### ISSUE THREAD

**Issue by gitsomecrabs** [nothings/stb#481]
Sean:

Am having a real issue on getting good quality on small size fonts on Opengl es 2.0.

I am building glyphs exactly for the size and resolution of the display.  (No texture expansion or contraction using UV coordinate manipulation) 

At a minimum, there needs to be a least 1 pixel on every row that is full 255 value.  When I render small size fonts (like 3mm), it loses that crisp bold look like I get when I render larger sizes.

Or do you think it would just be easier to patch the output of the rasterizer for small size fonts
and go back and look at each row and if the row does not have at least one 255 value, look for the highest alpha value and set it to 255.  That will take care of 1 pixel wide glyphs.  And if the glyph has multiple peaks, then set alpha at least once per peak.

I really hate the idea of including a library like FreeType when I can just focus on your compact code to make the small changes to improve the small size appearance.

Maybe even have a parameter that turns off aliasing for the rasterizer?
( stbtt_MakeGlyphBitmap( x,x,x,x,x,galiasing=false);

Your comments?

**Comment by nothings** [comment]
Forcing some pixels to be fully on is pretty much the way hinted, non-AA fonts work. So trying something hacky along those lines seems pointless compared to going the hinting route. But there's no hinting support in stb_truetype, and I don't expect there to be.

**Comment by gitsomecrabs** [comment]
Ok, thanks, I will add low resolution code accordingly. Cheers.

**Comment by ocornut** [comment]
> But there's no hinting support in stb_truetype, and I don't expect there to be.

@nothings Out of curiosity, are you saying this because you expect it to be too difficult or costly to be done right? Or would it affect the architecture noticeably and create other issues with the library? Or do you think there are more practical solutions for rendering small text? 

(NB: I don't know how proper hinting works at all. I'm not actively pushing for it, just curious as to why there is a line drawn here, as I naively expected that in a few months/years it was the sort of improvement stb_truetype might eventually receive, if the right combination of skills/time/goodwill/funding happened).

Thanks.

**Comment by nothings** [comment]
The pressure to make very small font sizes look good has decreased due to generally rising device DPI, combined with the high size/complexity of hinting support (truetype hinting is in an embedded bytecode language which requires an interpreter, plus it requires a different 1-bit-output rasterizer with different rasterization rules).

**Comment by gitsomecrabs** [comment]
And when you go entirely SDF based, try imagining adding hinting to the distance fields!  Yikes.

**Comment by gitsomecrabs** [comment]
Sean, I have been using the SDF implementation and it is WAY better than rasterized text. Works VERY WELL. Smooth crisp font at all image sizes.
