### ISSUE TITLE
stb_sprintf.h and network byte order

### ISSUE THREAD

**Issue by mreinstein** [nothings/stb#497]
I'd like to pack messages and send them over udp sockets, and I'd like it work across big and little endian machines. I'm wondering if `stb_sprintf/snprintf` are usable as-is to do this. I don't see any `hto*` type functions implemented internally which handle ensuring things get converted to/from network byte order. But maybe I just missed them.

If this is a dumb question I apologize; I'm super rusty with c and still learning.

**Comment by nothings** [comment]
sprintf converts to strings, which is not really the best way to serialize binary data, and there's no corresponding sscanf to "unpack" the data. (Plus converting to strings doesn't generally 'pack' the data, it's more likely to expand it.)

But the output should be byte-order independent, since the output is 100% bytes.

**Comment by mreinstein** [comment]
I see. Thanks for the information!
