### ISSUE TITLE
std_image.h Linear RGB formula (stbi_loadf)

### ISSUE THREAD

**Issue by georgy7** [nothings/stb#508]
Hi, Sean!
Could you please clarify some points about `stbi_loadf`?

From the docs:

    Additionally, there is a new, parallel interface for loading files as
    (linear) floats to preserve the full dynamic range

What do you mean by `preserve the full dynamic range`?

As I understand, `stbi_loadf` loads sRGB (e.g. from BMP, PNG, JPEG), and it makes the reverse gamma correction.

From [Wikipedia article](https://en.wikipedia.org/wiki/SRGB):
![screenshot_20171012_045650](https://user-images.githubusercontent.com/564471/31475486-c9ace17e-af09-11e7-8e1a-51656e8420a7.png)

But there is no `(c+a)/(1+a)` in the method `stbi__ldr_to_hdr`.
There is no `c/12.92` either.

Is `stbi_loadf` for something else?
Is this just some other HDR (not the linear RGB)?
Or is this just an approximation?
Does this method even relate to the general image formats, or it is for some special HDR files?

Thanks.

**Comment by nothings** [comment]
"Preserve the full dynamic range" in the text refers to the possibility of loading files that have higher dynamic range, such as the HDR file format, which is encoded in floats in the file. If there was no HDR interface, the data would have to be loaded through the prior 0..255 interface, and the dynamic range of the float data in those files could not be preserved.

The HDR interface does not load jpgs and pngs as sRGB, but using a settable gamma which defaults to 2.2, which is similar to but not identical to sRGB. Read the "gamma" section of the article you linked to. It would be possible to add the option to configure the HDR interface to do proper sRGB decoding, but it's not an interface that's intended for normally loading jpgs etc., it's just provided as a reasonable fallback in case you happen to do so, so adding explicit sRGB decoding has never been a priority.

**Comment by georgy7** [comment]
Understood. Thank you.

**Comment by senthuran-lkn** [comment]
hey guys sorry if I post this in wrong thread, but is there anyway of querying whether the image is srgb or lrgb. In our project we abstract the stb_image library in to our own interface, when loading images whether  srgb/ lrgb we need to  keep the information so that we can do something about it like converting to lrgb in shaders. I don't seen any function in stb_image to query for this information. any ideas?

**Comment by nothings** [comment]
stb_image supports 3 kinds of files:

* 8-bit-per-channel files
* 16-bit-per-channel files
* float-per-channel files

Preferably, you should use an interface that is the same size as the data--load 8-bit-channel files as 8-bit data, load 16-bit-files as 16-bit data, and load float files as float data.

The closest answer to your question is that there is a query (stbi_is_hdr) to detect if a given file is float-sized. However, there is no query to detect if a given file is 16-bit sized. So you kind of require out-of-band knowledge about this.

We DO allow you to load them as different sizes, but our handling of these cases are not ideal.

* 8-bit files are generally assumed to be gamma-encoded in some form, but stb_image doesn't actually support querying the gamma/srgb because many file formats don't have any mechanism for specifying. We should probably have an open issue for adding support for querying gamma/srgb-ness and support it for PNG and any other formats that support it. Then we could use this info when converting to 16-bit and float, instead of using stbi_ldr_to_hdr gamma.

* 16-bit files we currently convert to 8-bit by truncating the bottom 8 bits, but this is probably wrong since 16-bit files are probably linearly encoded, but it's not entirely clear if that's true. We should support converting the 16-bit files directly to float, but I don't believe we do. See #227

* float files, which we convert to 8-bit by using stbi_hdr_to_ldr_gamma and stbi_hdr_to_ldr_scale.

Fixing all of this to work right involves multiple different changes, all of which should be opened as separate issues.
