### ISSUE TITLE
dds support

### ISSUE THREAD

**Issue by nothings** [nothings/stb#518]
Add a dds loader, but not same model as HDR loader--we do not support converting to RGBA. It's really just there as a helper function for people who are writing 3D-accelerated games, because it's a poor use of everyone's time for them to not have this.

**Comment by raysan5** [comment]
In raylib I implemented support for DDS, PKM, KTX, PVR and ASTC data loading. Maybe any of those could be useful: https://github.com/raysan5/raylib/blob/develop/src/textures.c#L1852

**Comment by nothings** [comment]
@raysan5 License means I can't use your code, but thanks.

**Comment by Krakean** [comment]
@nothings any progress on this? :)
Would be nice to have support for DXT1/3/5, at least. Ideally - with BC6H & BC7.

**Comment by kphillisjr** [comment]
I know that the DDS file format is well documented ( see: [DDS on Microsoft Developers Network](https://msdn.microsoft.com/en-us/library/windows/desktop/bb943990(v=vs.85).aspx)). This should help with implementing the dds file format after using the recent source release by Rich Geldreich for a bc7 encoder. ( see: https://github.com/richgel999/bc7enc16 ). This should help since the code is released under the same license as the rest of the STB libraries.

Also, I will post something under issue #203 since this really should belong as it's own library set.

**Comment by raysan5** [comment]
@nothings sorry, just missed your comment! 

What's the problem with current zlib license? I can just relicense or dual-license that code if required.

**Comment by nothings** [comment]
stb_image is public domain, so you'd have to disown copyright for your lib. I wouldn't bother, dds isn't complicated enough to need that much work anyway.

**Comment by codedreality** [comment]
Maybe this helps, someone based on stb_image and implemented dds support.

https://www.lonesock.net/soil.html

**Comment by stephendb** [comment]
This would be a nice addition, soil itself is very old, would be nice to move the dds support into stb_image.

**Comment by jamesford42** [comment]
I need dds support and am probably going to rip it from soil. It is shown as having a public domain license. Any interest in me submitting a PR with this?

**Comment by nothings** [comment]
On reflection I think it's not worth integrating it into stb_image because the requirements are just too different. A texture loading library that wraps or requires stb_image is the right thing, really.

**Comment by alexpanter** [comment]
@nothings hi, old topic, but might one suggest a new header akin to `stb_dds.h`, which does "the thing" ?
