### ISSUE TITLE
Loading Image with desired channels error

### ISSUE THREAD

**Issue by Tom-III** [nothings/stb#551]
I have 2 PNG images that are the exact same except the one is 24 bit and the other is 32 bit (alpha) loading the 32 bit and 24 bit image yield different results even though the desired channels is set to 4?
The color array from the 24 bit image is 3072 long whereas the 32 bit image is 4096 long, what exactly is going wrong?

**Comment by nothings** [comment]
This works correctly; I've used it for a decade. You are probably not setting the desired channels to 4.

**Comment by nothings** [comment]
Actually, more likely it's *working*, but you're not understanding it correctly. Your assumption that the return length is 3072 wrong is probably incorrect because you're probably misinterpreting the third parameter, which as the documentation notes, is *number of channels in the file*, not the number of channels loaded. (If you specify 4 channels, then you know the file is loaded with 4 channels, and you can ignore the third parameter.)
