### ISSUE TITLE
stb_vorbis.c: Dead assignment, initialization, Assigned value is garbage or undefined

### ISSUE THREAD

**Issue by Martinfx** [nothings/stb#583]
Hi , scan-build reported on lines

Dead store | Dead initialization | stb_vorbis.c | start_decoder | 3429 |
-- | -- | -- | -- | -- | 
Dead store | Dead assignment | stb_vorbis.c | stb_vorbis_stream_length_in_samples | 4497 |
Dead store | Dead assignment | stb_vorbis.c | stb_vorbis_get_samples_short | 4830 | 
Dead store | Dead assignment | stb_vorbis.c | stb_vorbis_get_samples_short_interleaved | 4810 | 
Logic error | Assigned value is garbage or undefined | stb_vorbis.c | get_seek_page_info | 4171 |
Logic error | Result of operation is garbage or undefined | stb_vorbis.c | get_seek_page_info | 4164 |

**Comment by rpvelloso** [comment]
https://github.com/nothings/stb/blob/master/stb_vorbis.c#L4654 'offset' is used uninitialized here...

**Comment by rygorous** [comment]
This bug report does not mention which version of stb_vorbis it applies to; it's not the current version as of the time the bug was filed so I have no idea what the line numbers apply to, and it looks like at least some of these issues have since been fixed. Closing for lack of actionable information.
