### ISSUE TITLE
Should stbi_load_from_memory use size_t for its len argument?

### ISSUE THREAD

**Issue by BareRose** [nothings/stb#591]
First off, I'm only talking about `stbi_load_from_memory` and its variants (i.e. the other `_from_memory` functions), and only the `len` argument. All the other arguments are perfectly fine as they are.

The `len` argument is currently an `int`, which isn't necessarily wrong. However it describes the _size_ of a buffer _in memory_ measured _in bytes_. That's as textbook a use-case for `size_t` as it gets.

This is primarily a semantic issue, though it could have practical benefits on platforms with a 16bit `int` seeing as images often exceed the 32KB size limit imposed by such an `int`.

**Comment by nothings** [comment]
I doubt stb_image will be useful on 16-bit platforms in the first place.

As to whether to use size_t or to use int, it's pretty simple. IMO C made the wrong choice by using making size_t unsigned, because it makes size_t and ptrdiff_t require casts between them, and it means things like writing loops is a lot worse. (Consider a down-counted loop over a buffer whose length is size_t.)

Most of the time in stb libs I've gone with an older convention in which if you use ints for everything you end up needing a lot fewer casts. But this does mean if you don't use that convention you have to cast the size. If I made it size_t, people who habitually use int would be the ones having to cast. Neither way is ideal, so I went with the way that matches my coding convention. As a bonus, if I can convince more people that size_t is a waste of time, hooray.

**Comment by BareRose** [comment]
> As a bonus, if I can convince more people that size_t is a waste of time, hooray.

Funnily enough, I don't disagree that `size_t` is pretty horrible. IMO the biggest issue isn't the type itself but people over-using it on things that aren't sizes but merely size-adjacent (like array indices). Upon someone's suggestion over on Code Review I gave more liberal `size_t` usage a shot recently and it was the actual worst™. I now only use it on values that are actual sizes. Frankly it might even be too much to use `size_t` for sizes not measured in bytes.

> Neither way is ideal, so I went with the way that matches my coding convention.

Sounds reasonable. Thank you for explaining your reasoning!
