### ISSUE TITLE
stb_vorbis casue system crash on ESP-32

### ISSUE THREAD

**Issue by v1993** [nothings/stb#639]
I try to integrate stb_vorbis to ESP-32. However, various system crashes happens after calling open from memory. It is only one thing to do to crash ESP-32.

Can you help me, please? I think that https://github.com/nothings/stb/issues/583 can be related somehow.

**Comment by v1993** [comment]
I can't show any useful logs: crash happens in IDLE task (not in your code). But crash happens when calling your code and don't happens when not calling your code.

**Comment by jarikomppa** [comment]
Since stb_vorbis isn't ESP-32 specific, asking here is probably pretty
futile. You could follow the ESP-32 documentation (e.g,
https://arduino-esp8266.readthedocs.io/en/latest/faq/a02-my-esp-crashes.html
) or find an ESP-32 forum somewhere where you could ask.

That said, it's entirely possible something in the stb_vorbis code causes
the crash, by for example doing an un-aligned read in some way ESP-32
doesn't like, but that's pretty impossible for anyone to figure out without
having access to ESP-32 development tools. Which you have. So if you do
find some offending code, do comment about that, so things may be fixed in
the future.

**Comment by v1993** [comment]
It corrupts some memory (like place where information about tasks are stored), so other important things crashes, but it seems impossible to easily find problematic code (stack smashing protection + heap corruption prevention are enabled and still error). It writes to __valid__ ardress (which exists in memory, but in fact isn't expected), so no `LoadPhrobided` or `StorePhrobided` error.

Also, IMHO issue #583 can be related somehow. However, it is only my suggestion.

**Comment by jarikomppa** [comment]
Does this happen on every ogg, or a specific one?

**Comment by v1993** [comment]
I've switched to Tremor, so no more investigating this. Most probably that I had too small stack.

If I'll return to this library and get same error with bigger stack this issue will be reopened.
