### ISSUE TITLE
Simpler way to make antialiased font?

### ISSUE THREAD

**Issue by greggman** [nothings/stb#648]
Thank you so much for this library

I'm planning to support anti-aliasing by rendering a font with oversampling then walking over each glyph and bilinear interopolating back to the non-oversampled size. In other words I want a font with 10x10 pixels but I want to generate it from 40x40 size glyphs?

I just wanted to ask if that's the *correct* thing to do?  

Right now I'm hacking through a copy of `stbtt_PackFontRangesRenderIntoRects` and I'm basically going to render each glyph into a temporary buffer, bilinear them back into width / oversample, height / oversample, then put the result into the rect.

Sorry if this is a dumb question, just trying to avoid going down the wrong path if I should be doing something else.

**Comment by nothings** [comment]
You don't need oversampling, they're already anti-aliased. All API functions that generate bitmaps generate anti-aliased bitmaps.

**Comment by greggman** [comment]
Thanks, I guess I didn't explain myself.  I want more antialiasing. For example in Photoshop there are 4 settings: none, crisp, smooth, sharp so was wondering the best way to approach that. Can set the font size larger and scale down. Can oversample and scale down, Other ...

**Comment by nothings** [comment]
Setting the font size larger and scaling down will just get you the same result as building the font normally, since that's the same math that the existing anti-aliasing does.

I don't know for sure what Photoshop does, but it may just be running each pixel through a function, like if each pixel is x=0..1 it does sqrt(x) or x*x. You can do this on your own after stb_truetype produces a pixel.

Oversampling and then scaling down is just going to introduce a slight blur, and probably not a useful one.
