### ISSUE TITLE
maximum image size for sub_image

### ISSUE THREAD

**Issue by xelatihy** [nothings/stb#672]
Trying to load large HDR images, such as the 16k HDRI from https://hdrihaven.com, casus problems. I track the problem to the function `stbi__mad4sizes_valid` that returns false for large images. It would be good if it were possible to specify the largest image size allowed or have the limit lifted.

**Comment by nothings** [comment]
The size limit is different between 32-bit and 64-bit platforms. On 32-bit platforms, a 16K x 8K HDR decoded as RGBA is going to be 4 channels * 4 bytes per channel * 16384 * 8192 = 2^(2+2+14+13) = 2^31 bytes. This number is larger than INT_MAX (which is 2^31-1), and even if we relaxed that limit to UINT_MAX so it fit, it is unlikely that the malloc would succeed.

Since we cannot predict whether malloc would succeed or not, there's not much we can do in general.

On 64-bit platforms it should load fine.

**Comment by nothings** [comment]
The above math assumed you were trying to load it as 4 channels by setting desired_channels to 4. If you set desired_channels to 3 (or 0), I believe it should just barely fit in 32-bit platforms and I would expect it to load successfully, assuming you haven't allocated much other memory and your memory space isn't fragmented. But you're still playing with fire, basically.

**Comment by nothings** [comment]
My mistake, it still won't work on most 64-bit platforms, it only works on so-called "ILP64" platforms where integers are 64-bit. None of Windows, MacOS, nor Linux are ILP64 platforms, so it won't work on anything mainstream. I suppose this is fixable in theory, but the use of bare 'int's instead of 'size_t' permeates the code and maybe would be an enormous amount of work to fix, since the change would need to be made independently to every file format. I think that goes on the "someday" list, since memory and image sizes are just going to keep growing.

**Comment by rygorous** [comment]
Labeled as documentation bug since we should at least state the limit explicitly.

**Comment by RafigRzayev7** [comment]
Wanted to share clarification on this topic, maybe could prove useful for users and for doc. update.

From stb_image.h: 

> // stb_image uses ints pervasively, including for offset calculations.
> // therefore the largest decoded image size we can support with the
> // current code, even on 64-bit targets, is INT_MAX. this is not a
> // significant limitation for the intended use case.

Size of INT is implementation dependent, but is 4 bytes on most systems:
4 bytes = 32 bits = 2^32 = 4294967296 values, i.e [0, 4294967295]

But since we use signed integers, the MIN / MAX values are:
  INT_MIN =  - (2 ^ 32) / 2 = - 2147483648
  INT_MAX =  (2 ^ 32) / 2 - 1 = 2147483647  // _subtract 1 to include zero_

Thus,
 
MAX_IMAGE_SIZE = 2147483647 Bytes // **_bits instead of bytes would result in ~256MB max._** 

To convert Bytes to MB (Megabytes), 2 notions could be used. Normally, Mega means 10^6, but in memory context usually MB = 2^20 B = 1024*1024 B = 1048576

So, 

MAX_IMAGE_SIZE = ( 2147483647 / 1048576 ) MB = 2047.999999046 MB ≈ 2048 MB

**MAX_IMAGE_SIZE  = 2 GB**

_So, for a 4 channel image with identical width & height, I believe maximum dimensions would be:_
23170 x 23170 -> SIZE = 23170 x 23170 x 4 = 2147395600 < INT_MAX
23171 produces overflow -> SIZE = 23171 x 23171 x 4 = 2147580964 > INT_MAX
_Or, for a 1 channel grayscale image max. dimensions would be_: 46340 x 46340

**Comment by nothings** [comment]
Also, PNG has an explicit threshold of max 1GB output, which could (should?) probably be weakened to 2GB on 64-bit machines. (Because of the full-sized intermediate zlib data decode, I think 2GB will never work in 32-bit.) JPEG doesn't appear to have any limit except the INT_MAX math limit.

**Comment by rygorous** [comment]
The image size limit will stay for the time being (for API stability reasons), but this is now more clearly documented in the dev branch, and that new explanation will make it into the next version, so once we merge dev this issue should be considered resolved.
