### ISSUE TITLE
Subpixel Image Resize Confusion

### ISSUE THREAD

**Issue by vamalo** [nothings/stb#692]
Is the following code supposed to work?

        stbir_uint8 input[32*32*4];
        stbir_uint8 output[32*32*4];
        stbir_resize_subpixel(
            input,32,32,0,
            output,32,32,0,
            STBIR_TYPE_UINT8,4,3,0,
            STBIR_EDGE_ZERO,STBIR_EDGE_ZERO,
            STBIR_FILTER_DEFAULT,STBIR_FILTER_DEFAULT,
            STBIR_COLORSPACE_LINEAR,NULL,
            0.5,0.5,0,0);

Since the scale is 0.5 and the border is black, I expected the output to contain the input image in the top-left corner and everywhere else to be black.  Instead, I got an assertion failure on line 1102 of stbir__normalize_downsample_coefficients, suggesting that I'm not allowed to sample pixels outside the source image.

STBIR_ASSERT(total > 0.9f);

**Comment by nothings** [comment]
I believe this is not expected to work, I think stb_image_resize is only designed to compute output pixels that are correspond to at least one input pixel, so it wants output,16,16 or some such.

**Comment by technosaurus** [comment]
The function def looks like:
```c
STBIRDEF int stbir_resize_subpixel(const void *input_pixels , int input_w , int input_h , int input_stride_in_bytes,
                                         void *output_pixels, int output_w, int output_h, int output_stride_in_bytes,
                                   stbir_datatype datatype,
                                   int num_channels, int alpha_channel, int flags,
                                   stbir_edge edge_mode_horizontal, stbir_edge edge_mode_vertical, 
                                   stbir_filter filter_horizontal,  stbir_filter filter_vertical,
                                   stbir_colorspace space, void *alloc_context,
                                   float x_scale, float y_scale,
                                   float x_offset, float y_offset);
```
So I would imagine, you want:

```c
    stbir_uint8 input[32*32*4];
    stbir_uint8 output[32*32*4];
    stbir_resize_subpixel(
        input,32,32,0,
        output,16,16,16, /* <-- changes here */
        STBIR_TYPE_UINT8,4,3,0,
        STBIR_EDGE_ZERO,STBIR_EDGE_ZERO,
        STBIR_FILTER_DEFAULT,STBIR_FILTER_DEFAULT,
        STBIR_COLORSPACE_LINEAR,NULL,
        0.5,0.5,0,0);
```

**Comment by nothings** [comment]
output,16,16,0

**Comment by technosaurus** [comment]
Wouldn't that put the second line to the right of the first instead of placing the image in the upper left corner. 

IIRC the stride (and offsets) allow you to draw a smaller image anywhere on a larger output buffer (it's been a while though, so correct me if I am wrong)

  I used something like that to draw a small png based symlink symbol on a larger icon and then to draw the icon on the linux framebuffer

**Comment by nothings** [comment]
It depends what they want to do. If they WANT the smaller image to be a corner of a large space, they can do it by setting the stride, but not to the value you indicated. First of all, if the larger image is 32 wide, stride needs to be 32 pixels wide, not 16; but furthermore, the stride is measured in bytes, not in pixels. I always err on describing the simplest case in examples like this because it's not clear that people actually WANT the crazy behavior, just that they're describing what they expect to happen.

Moreover, if they want a small image inside of a larger image, they can start by making the small image directly and copying it into the large image themself. That makes the problem of learning how to copy a small image to a large image NOT our problem and lets us close the issue and let him go learn that somewhere else.

**Comment by technosaurus** [comment]
I fixed the code above to be in bytes instead of pixels, but that is the second time I misread the docs on stride because of "offset between" ... 99% of the time an "offset between" 2 things doesn't include the length of one of those things.  Here stride means the same as it typically means ... offset in bytes between the start of 1 row of image data and the next, but the docs almost make it sound like it's actually the length in bytes of just the padding between rows of image data.

> stride is the offset between successive rows of image data in memory, in bytes. you can   specify 0 to mean packed continuously in memory

The ability specify 0 to mean packed continuously reinforces that misinterpretation since that is what the offset would be between the end of one row and the beginning of the next.

**Comment by nothings** [comment]
Feel free to open a separate issue for the documentation error. I stand by my other points.

**Comment by nothings** [comment]
no response from original user for a month, closing
