### ISSUE TITLE
How compiling example?

### ISSUE THREAD

**Issue by letarg0** [nothings/stb#724]
For example text editor?

**Comment by nothings** [comment]
https://github.com/nothings/stb/blob/master/tests/textedit_sample.c

**Comment by letarg0** [comment]
Any makefile?

**Comment by nothings** [comment]
There is no need for a makefile to build header-file-only libraries. For all stb libraries that are a .h file, all that's needed is:

  #define STB_TEXTEDIT_IMPLEMENTATION
  #include "stb_textedit.h"

There is no standalone example for stb_textedit.h because it has so many input/output requirements it's not feasible to make a working cross-platform example.

**Comment by rajhlinux** [comment]
Are there any real working examples which can be compiled?

I would like to know how I can use the "stb_textedit.h" header file and create a very basic text editor. Which functions and data structure to implement.

Thanks.

**Comment by nothings** [comment]
No, there are no real examples of stb_textedit in the project. You could look at https://github.com/ocornut/imgui/blob/master/imgui_widgets.cpp#L3879
