### ISSUE TITLE
(stb_image_resize) Assert triggered on float comparison with 0

### ISSUE THREAD

**Issue by nyeecola** [nothings/stb#736]
I'm not sure what exactly this assert does, but it was triggered:

line 1105: 
`STBIR_ASSERT(stbir__filter_info_table[filter].kernel((float)(out_last_pixel + 1) + 0.5f - out_center_of_in, scale_ratio) == 0);
`

Should it really compare with zero like this? Or should it have a tolerance because of floating point math inaccuracy? I can make a pull request if it is indeed a mistake.

**Comment by trebconnell** [comment]
I hit this as well.  I was resizing an image where the x axis was a downsample and the y axis was an upsample.  The image was also much larger than other images I've resized.  I don't know which of these lead to the assertion triggering.  The produced image is still okay if I comment this out.

**Comment by trebconnell** [comment]
Threw together a repro here.  If I divide all the dimensions by 2 this doesn't repro, which seems to suggest it is related to the large size of the input.   If I pass smaller width/height it doesn't repro.  I also tried cubic b spline and it didn't repro, so this appears box filter related.

```cpp
    const auto width = 9795;
    const auto height = 9795;
    const auto newWidth = 16384;
    const auto newHeight = 16384;

    std::vector<char> img(width * height);
    std::vector<char> out(newWidth * newHeight);

    stbir_resize(img.data(), width, height, width, out.data(), newWidth, newHeight, newWidth, STBIR_TYPE_UINT8, 1,
                 STBIR_ALPHA_CHANNEL_NONE, 0, STBIR_EDGE_CLAMP, STBIR_EDGE_CLAMP, STBIR_FILTER_BOX, STBIR_FILTER_BOX,
                 STBIR_COLORSPACE_LINEAR, nullptr);
```

**Comment by nyeecola** [comment]
I think you're right, maybe it happens more frequently with larger images. However, some of my images aren't that large and still trigger the assert.

About this being box filter related, I'm pretty sure it has happened to me at least once on one of the other filters as well but I don't remember which one right now. It definitely seems to happen more with box filter though.

I'll look into this later today.

**Comment by BSVino** [comment]
Hello I’m the code author and I’ve been busy and at GDC but I pledge to look into this when things settle down after the conference. Sorry for the delay.

**Comment by trebconnell** [comment]
Thanks!  Also thanks for making one of the few resizing libraries that has
box filter.

**Comment by robinvanemden** [comment]
Thanks for stb and stb_image_resize.h, @BSvino & @nothings! We use stb in an image conversion pipeline, generally works like a charm 😄 

We do still encounter the current issue, though.

As @nyeecola suggested, the problem seems to result from basic floating point math inaccuracies. For problematic images (their size is irrelevant) the operant to the left generally yields 0.000001 at some point while looping through the image's pixels. On further investigation, I think the source of the floating point inaccuracies can be traced, for instance, [here](https://github.com/nothings/stb/blob/b42009b3b9d4ca35bc703f5310eedc74f584be58/stb_image_resize.h#L2231-L2232).

Still, on removing the assert, the resulting resized image is perfectly fine. So there seem to be several ways to resolve this:

- delete [the relevant assert](https://github.com/nothings/stb/blob/b42009b3b9d4ca35bc703f5310eedc74f584be58/stb_image_resize.h#L1106)
- check for "[nearly equal](https://floating-point-gui.de/errors/comparison/)".
- replace the assert

Do you have a preference for one of these options? I feel that deleting the assert would actually be the cleanest solution here, but each option has its pros and cons.

**Comment by nothings** [comment]
@BSVino is no longer supporting stb_image_resize. We have a rewrite in progress that fixes it, but no ETA. See this discussion (which just says the same thing): https://github.com/nothings/stb/issues/836#issuecomment-557773008

**Comment by robinvanemden** [comment]
Hi @nothings, thanks for the fast reply. As the library works fine when disabling asserts, we will be able to use it while awaiting the new version. But super that you have a rewrite in progress!

**Comment by rygorous** [comment]
This is now fixed in the dev branch and will be in the next release.
