### ISSUE TITLE
How to rander to 1bit bitmap font

### ISSUE THREAD

**Issue by poweel** [nothings/stb#785]
I want to use stb font in a single color lcd, how to rander to 1bit bitmap font. (2 level gray)

**Comment by zao** [comment]
As far as I can tell from documentation and functions, the functions that rasterise produce anti-aliased 8-bit images.
You could take these images and decide per-pixel against a threshold whether the pixel is on or off in an "alpha testing" manner, but it's going to look crude.

The library can also generate SDF (signed distance field) data which you can use to draw text by sampling the data field with your pixel positions and determining whether a pixel is inside or not. This is typically done when you want magnified text and may not look that good for small sizes.

Both these methods will have sub-par results if your LCD is low resolution, but might be fine otherwise.

**Comment by nothings** [comment]
You can only get low-quality 1-bit output by manually thresholding. Proper 1-bit output generally requires hinting and a different rasterizer.
