### ISSUE TITLE
stb_vorbis: The 'finalY[j]' variable was assigned the same value.

### ISSUE THREAD

**Issue by kcgen** [nothings/stb#885]
![image](https://user-images.githubusercontent.com/1557255/72758781-a222c480-3b88-11ea-9d16-b13d917fc03c.png)

https://www.viva64.com/en/w/v1048/

**Comment by rygorous** [comment]
While true, that code is a 1:1 transcription of the pseudocode from the Vorbis spec: https://xiph.org/vorbis/doc/Vorbis_I_spec.html#x1-1030007.2.4 ("step 1: amplitude value synthesis", line 39). I'd prefer to keep this matching the spec rather than introduce gratuitous differences to pacify static analyzer warnings.
