### ISSUE TITLE
stb_truetype.h x2 - x2 

### ISSUE THREAD

**Issue by Algo-ryth-mix** [nothings/stb#924]
While playing around with cppcheck for a project of mine it found this rather roundabout way of declaring zero. `x2-x2`. Not sure if this is a deeper issue, or an issue at all (or intended, in which case sorry to bother), just thought I would mention it.

https://github.com/nothings/stb/blob/f54acd4e13430c5122cab4ca657705c84aa61b08/stb_truetype.h#L3172

**Comment by nothings** [comment]
The x2-x2 was correct, but a few lines above was a computation "x1-1-x1" which I'm pretty sure was wrong.

I've rewritten the area formulas to make more sense and remove these sorts of issues. As well as rendering a few characters, I also looked at the values that were being generated for a couple straightforward configurations to make sure everything seemed reasonable.

Fixed in next release.
