### ISSUE TITLE
stb_vorbis_frame_pushdata() doesn't say how to dispose of output buffers

### ISSUE THREAD

**Issue by ghost** [nothings/stb#929]
stb_vorbis_frame_pushdata() doesn't say how to dispose of output buffers in this description text:

https://github.com/nothings/stb/blob/37b9b20fdec06c75a0493e0bb59e2d0f288bfb51/stb_vorbis.c#L215

Are the buffers owned by the stb_vorbis* object and will get free'd automatically during use, or at the latest with stb_vorbis_close? Or do I own them / am I supposed to free them? This info might be quite essential to avoid really bad memory leaks for the user, so I would expect it explained in that line I referenced.

The `sample.c` code doesn't seem to do anything with the output buffers, so if they *do* need to be freed I suggest to update that as well in addition to the text.

**Comment by rygorous** [comment]
The output buffers you get point into the stb_vorbis persistent internal channel buffers (same lifetime as the stb_vorbis object itself). You don't get ownership of them, are not supposed to free them, and indeed should consume the any data you want before you feed the decoder any more input because it will be overwritten. I'll clarify the docs in the header portion.
