### ISSUE TITLE
JPEG marker FFD1

### ISSUE THREAD

**Issue by photopea** [nothings/stb#952]
Hi, I am using your library for dcoding JPEG files. I ran into a file, which has a FFD1 marker, and it crashes the whole JPEG decoding process. Could you implement the support for this marker? It occurs in the file attached below (and all JPG viewers can open it).

![IMG_0015](https://user-images.githubusercontent.com/15955558/78931368-26108c80-7aa6-11ea-9ee8-589688f74a03.JPG)

**Comment by nothings** [comment]
generally, stb_image does support the FFD1 jpeg marker, so that may not be the reason for the crash. i'll look into it.

**Comment by ebraminio** [comment]
Bare minimum to reproduce:

```C
#define STB_IMAGE_IMPLEMENTATION
#define STBI_ONLY_JPEG
#include "stb_image.h"

int main() {
    FILE *f = fopen("test.jpg", "rb");
    unsigned x = 0, y = 0, comp = 0;
    printf("final size: %d\n", stbi_load_from_file(f, &x, &y, &comp, 4));
    printf("width: %d, height: %d, comp: %d\n", x, y, comp);
    fclose(f);
    return 0;
}
```

Gives

```
final size: 0
width: 0, height: 0, comp: 0
```

but `stbi_info_from_file` gives

```
final size: 1
width: 2576, height: 2704, comp: 3
```

mtPaint (probably libjpeg) logs this in console: `Corrupt JPEG data: 2047 extraneous bytes before marker 0xd1` so guess we can be more nice here.

**Comment by photopea** [comment]
@nothings are there any news? As I understand, this marker can be simply skipped.

**Comment by ebraminio** [comment]
And searching, "extraneous bytes before marker", it is apparently a famous defect between jpeg files, hopefully can be fixed here also.

**Comment by rygorous** [comment]
The problem is not with the FFD1 marker.

This file contains lots of extraneous data. At offset 0xb484b, data for all pixels in the image (as per SOF marker) has been specified, and the decoder returns. After that, we already end up in an error-recovery loop to handle malformed files that was added long ago (the "handle 0s at the end of the image data from IP Kamera 9060" case). But in this case, the data stream contains not just extra 0s, but several kilobytes of extra data, including multiple other markers (including several flavors of RST markers; it just keeps going as if there's extra data to specify and has several extra ECSes where they don't belong.

In short, this file is just fairly badly malformed, either it has incorrect dimensions in the SOF marker or just tons of extra data where it doesn't belong for some other reason. It is _definitely_ outside the scope of stb_image to deal with files like this. As per the mission statement at the top of the file, stb_image is "primarily of interest to game developers and other people who can avoid problematic images and only need the trivial interface". It's never been the point of stb_image file to load every JPG in existence, and files like this that get flagged as malformed not just by us but also by other tools are definitely not the kind of thing we expect to be able to handle.
