### ISSUE TITLE
stb_image.h outofmem on x86 release mode target

### ISSUE THREAD

**Issue by tim-rex** [nothings/stb#956]
I'm unable to put my finger on _why_ but I'm seeing _outofmem_ errors while calling:

```
		int texWidth, texHeight, texChannels = 0;
		stbi_uc* pixels = stbi_load(
			TEXTURE_PATH.c_str(),
			&texWidth, &texHeight, &texChannels, STBI_rgb_alpha);
```

The source image is: [https://vulkan-tutorial.com/resources/chalet.jpg](https://vulkan-tutorial.com/resources/chalet.jpg)

It's a 4096x4096 image.

Curiously, it's only in release mode targeting x86 that I'm seeing an issue (building on Visual Studio 2019 Version 16.5.4).

x64 builds work as expected in release mode.
Debug builds for both targets also seem fine.

I've tried building release mode without optimisations (/Od) but the issue persists.  I can't quite see where the differentiating factor is.

I'll see if I can distill this down to a minimal repro...  
I'm not overly concerned, x86 as a target isn't a big priority tbh.. but happy to help where I can.

**Comment by nothings** [comment]
Have you done other allocations before this? What happens if, after you get outofmem, you try to malloc(4096*4096*4+4096*4096*2)? If that fails, you're just out of memory.

(The above is 64MB for the image plus an estimated 32MB for intermediate buffers.)

You can put a breakpoint in the function stbi__err and see what the calling location is, but since this only happens in release they may not give you useful information.

**Comment by tim-rex** [comment]
Well now I feel quite silly. Who knew outofmem might actually mean exactly that.

I guess I expected to be subject to the same 32-bit limits wether I'm in release mode or not :-/
Thanks and apologies for the time waste.
