### ISSUE TITLE
Memory requirements for JPEG decoding

### ISSUE THREAD

**Issue by photopea** [nothings/stb#964]
Hi, I am using your JPEG decoder in WASM environment. It is necessary to know in advance, how much memory the WASM program will require (to allocate it before running a program).

The program should store at least the input and the output. The output is four bytes per pixel, so it needs at least:

    Memory = inputSize + Area * 4

I am using the following formula to predict the memory usage:

    Memory = 5,000,000 + inputSize * 2 + Area * 7

It works well for hundreds of files, except of the file below. Do you think you could improve the memory requirements of the decoder? What formula should we use to predict the memory?

![DXWP84334 - outside](https://user-images.githubusercontent.com/15955558/81862884-abd29c80-956a-11ea-91bc-5b612d4651b2.jpg)

**Comment by nothings** [comment]
Memory requirements depend on the format of the image.

JPG images are first decoded into an image in YCbCr format. In most such images, the Y channel is stored at the same resolution as the output size, but the Cb and Cr channels use 1/4 the memory. However, some images may use full-size Cb & Cr channels. Thus the only safe estimate is

input_size + output_size + 3*w*h + fixed_overhead

**Comment by nothings** [comment]
Since your area = w*h, that means area*(4+3), which is the area*7 that you are already using. I don't know why that isn't sufficient offhand for this image, but I'm also not really interested in figuring out why.

**Comment by photopea** [comment]
I tried to use use area * 10, but it is still not enough for the image above.

I thought this library could be used in low-memory environments. When you want to decode a 30 MPx image, the result will have 120 MB. But your library fails even with 300 MB of memory.

The fact, that you do not guarantee any memory limits of your program, can be considered a bug. There could exist a relatively small JPG image, which will make your library chrash even with 4 GB of RAM.

What should be the ratio between the memory requirements vs. the output image size, that would make you care about it?

**Comment by nothings** [comment]
The library is not intended for, and is not billed as, being appropriate for low-memory environments. It fully decodes the image into an intermediate format (the 3 * w * h above), which is not necessary for most images (although there are some images where it's required). But it's not designed to be optimal for space. libjpeg is far more space efficient, since it avoids that intermediate size when it can.

It's also trivial to make the library try to allocate 1GB by making a tiny JPEG with a header that claims the output image is very large. So that's not really very interesting.

But yes, an image that uses an unexpectedly large amount of temporary memory could be a bug, but it also might just be me forgetting about some source of temporary memory allocation in code I wrote 12 years ago.

So I'm not going to PROMISE to fix, but sure, if you have an image that uses more than

    w*h*12 + (w*32) + (h*32) + input_size*2 + 65536

that would be pretty surprising.

**Comment by nothings** [comment]
Also, you can look at this document to better understand how sometimes libraries cannot easily predict their memory requirements: http://nothings.org/gamedev/font_rendering_malloc.txt

**Comment by photopea** [comment]
w*h*12 + (w*32) + (h*32) + input_size*2 + 65536

that is exactly the image above. It is 3207 x 2231, and your formula gives 92,017,842 Bytes, which is not enough.

I understand, that it can be hard to work on code you made many years ago. But I really appreciate the fact, that this library is so small. If you could look into it, I could donate $100 - $1000 to this project, because I really like it :)

**Comment by nothings** [comment]
I don't take donations, as there is no way for me to turn donation money into more work on the libraries.

**Comment by nothings** [comment]
Yep, like I said, I don't remember everything required. In this case, it's a PROGRESSIVE jpeg.

PROGRESSIVE jpeg with no color downsampling requires an additional 2-byte-per-channel intermediate buffer, so that's an extra w * h * 6 bytes.

Which means the expected cost proportional to area is area * 13. My guesstimate above of w * h * 12 was one too small.

**Comment by nothings** [comment]
Feel free to comment further, but I'm closing it since I don't think there's a real issue here.

**Comment by photopea** [comment]
You can look at my donation as a one-time payment for a one-time job of improving your library (and helping the world)! :) Do you think it would take you an hour or two to improve the memory requirements and fix a possible bug? So what is your usual salary per hour? :D

**Comment by nothings** [comment]
There is no straightforward way to reduce the memory requirements. stb_image is designed to use simple code. It would have to get overly complicated to save memory.

Since you have to forbid large images in the first place to predict the size requirements, you could just forbid progressive JPEGs as well.

**Comment by photopea** [comment]
Are you sure there is no simple way to use less memory? Maybe you could reuse an old array in some part of the code, instead of allocating a new one.

But, please, tell me honestly. Maybe you really have a strong subconscious aversion towards having to modify your old code, and you are trying to rationalize it. Maybe I am wasting my time here :/

**Comment by nothings** [comment]
You are wasting your time (and mine).
