### ISSUE TITLE
stb_image.h error loading bmp from memory.

### ISSUE THREAD

**Issue by haozhan** [nothings/stb#994]
![stb_bug](https://user-images.githubusercontent.com/7542479/87393373-a9c7a100-c5e0-11ea-9731-8b88dfb6b140.png)

s->buffer_start is an uninitialized abandoned array (pointer) when loading bmp picture from memory, using it for an error.

**Comment by haozhan** [comment]
I took a look at the logbook, this problem has long been feedback and solved. But the old code problem comes back from merging with a branch.
The specific version is:
Merge branch 'stb-image-fuzzing-fixes' of https://github.com/rcgordon… …
Sean Barrett committed 4 days ago

![DevCap_20200717_161949](https://user-images.githubusercontent.com/7542479/87765463-6c664c00-c84a-11ea-8ba7-fc2f107cc705.png)

 the problem of merging the above version.

**Comment by nothings** [comment]
ah, good catch, thanks.

**Comment by Moros1138** [comment]
I can confirm this issue and offer what appear to be, at least on my end, the solution.

My code that I used to test it:

```
data = stbi_load_from_memory((stbi_uc*)vecMemory.data(),.vecMemory.size(), &width, &height, &channels, 4);
```

returns NULL and if you run ``stbi_failure_reason`` you get "bad offset" or "Corrupt BMP" depending on whether the ``STBI_FAILURE_USERMSG`` is defined.

I was able to fix it locally by changing the code at around line 5298 (in the latest header) from: 

```
      if (info.offset != s->callback_already_read + (s->img_buffer - s->buffer_start)) {
```

to the following
```
      if (info.offset != s->callback_already_read + (s->img_buffer - s->img_buffer_original)) {
```

This resolved the error messages and restores the expected behavior of the function. Looking forward to an update.

P.S. Thanks for all the work you and your collaborators put into this project. It is truly awesome!

**Comment by ITotalJustice** [comment]
> img_buffer_original

Thanks mate, your suggestion fixed the issue for me as well.

**Comment by ClysmiC** [comment]
This issue is still outstanding. I am consistently hitting the assert on 32bpp bmp's exported with paint.net. My bitmap has a 124 byte header (+ the extra 14 bytes represented by "extra_read"), and the pixel data has a 150 byte offset into the file. It looks like the assert is complaining that my pixel data isn't immediately following these initial 138 bytes, but I don't think that BMP has any such requirement. In fact, the assert is over-cautious, as the subsequent stbi__skip call correctly skips to a 150 byte offset. If I entirely comment out the "if (psize == 0)" statement, my image loads without issue.

I propose that the error check be removed entirely.

**Comment by JakobBieling** [comment]
While not a fix: a viable workaround is to use `stbi_io_callbacks` for providing data from a buffer ... works for me, at least until this issue is fixed.
